### ISSUE TITLE
@:forward not helps to resolve symbols in abstracts

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#108]
Plugin version: [latest build](https://github.com/TiVo/intellij-haxe/blob/314e4e87dd12e8e2f18893cf105c04b5ef7f382e/intellij-haxe.jar).

![screen shot 2015-01-11 at 19 36 54](https://cloud.githubusercontent.com/assets/888526/5695926/6c9e9a2a-99c9-11e4-91ae-e7e4e8302a4e.png)

Full source for reproduce:
````haxe
package ;
class Demo { public static function main() { new Bar(); } }

private class Foo
{
	public var a:Int;
	public var b:Int;
	public function new(){}
}

@:forward // This suggests that we get all the fields from `Foo` mentioned in next line: "..abstract Bar(>>>>Foo<<<<).."
private abstract Bar(Foo) from Foo to Foo
{
	public function new()
	{
		this = new Foo();
		this.a = 1;
		this.b = 2;
	}
}
````

**Comment by as3boyan** [comment]
There is no `forward`-specific implementation yet. So it seems like abstract should have same fields, similar to `extends` or `implements` functionality...

**Comment by fzzr-** [comment]
Yes, you right.

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/17b83665d7be99943b1c662b70231300008db038

**Comment by EBatTiVo** [comment]
@fzzr- It would be great if you can test and verify this.
