### ISSUE TITLE
Colors / CodeParsing is different

### ISSUE THREAD

**Issue by joergwasmeier** [TiVo/intellij-haxe#112]
Hi,

when i use the ClassHierarchy Branch Plugin the Parsed Code have different Colors than with the stable Plugin.

Stable Plugin
![repo](https://cloud.githubusercontent.com/assets/10448310/5954736/a8f8c024-a79b-11e4-9a3b-3f4bb3576ac8.png)

ClassHierarchy
![classhierachy](https://cloud.githubusercontent.com/assets/10448310/5954739/ad7db67c-a79b-11e4-99a3-0fb5740a61ac.png)

**Comment by grisevg** [comment]
Duplicate of #54 . It's actually really important feature.

**Comment by Faba-network** [comment]
Hmm well i don´t use conditional compilation tags in my code so this is perhaps another bug?!

**Comment by grisevg** [comment]
I'm an idiot. I meant #52

**Comment by Faba-network** [comment]
Okay, yeah quite similar, its just not only variables functions also have a parsing problem.

**Comment by EBatTiVo** [comment]
Dup of #52.  We'll leave that one open.
