### ISSUE TITLE
error using

### ISSUE THREAD

**Issue by WeyskoteFoundation** [TiVo/intellij-haxe#116]
![haxe](https://cloud.githubusercontent.com/assets/4976223/6014468/81883b6a-ab4b-11e4-8974-1ad00ebd5086.png)

https://github.com/andyli/jQueryExternForHaxe/blob/master/jQuery/haxe/Utils.hx

**Comment by EBatTiVo** [comment]
Similar to issue #55?

**Comment by EBatTiVo** [comment]
Works on build 0.8.1.1.TiVo.ClassHierarchy.11.  This will be coming down to master as soon as it's stable.

```haxe
package ;

import StringTools;

class Issue116 {
    public function new() {
    }
    public static function main():Void {

        trace(StringTools.htmlEscape("<ul><li>some &gt; text &lt; </li></ul>"));
    }

}

```
