### ISSUE TITLE
Cannot compile lime/openfl project

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [TiVo/intellij-haxe#118]
Hey,

When I try to compile my lime/openfl project (target: linux64) I get:

```
Information:04.02.15 14:27 - Compilation completed with 1 error and 1 warning in 0 sec
Error:Compilation failed
Warning:This is not a real warning, it's just here to force this window to open ...
/home/ls
Information:Uncaught exception - load.c(181) : Module not found : run
```

When I do "lime test linux" on the command line, it works.
Any Ideas? Any informatin I should post about my installtion?
newest intellij-haxe-jar installed and using haxe 3.1.3.

TIR: STB-7327

**Comment by as3boyan** [comment]
Is your OS 32 bit or 64?

**Comment by EBatTiVo** [comment]
Can you clarify what the "newest intellij-haxe-jar" means?  (i.e. newest from where?)  What is the version string reported in IDEA when you look at the plugin support page? (File->Settings->(left panel)plugins->(middle panel)Haxe support)

**Comment by as3boyan** [comment]
I think it's just wrong parameters or target options passed to `openfl`, maybe it attempts to build 64 bit on 32 bit OS, not sure

**Comment by RudolfVonKrugstein** [comment]
My os 64bit. I tried to target linux/linux64/flash, all the same result.
With "latest" I mean the intellij-haxe.jar from this repository (master). The version displayed in idea is:

```
0.8.1.1.TiVo.3: (TiVo version)
```

**Comment by RudolfVonKrugstein** [comment]
The problem still exists. Can I somehow make the intellij plugin output the lime/haxe command it runs?

**Comment by EBatTiVo** [comment]
Try the [build on the ClassHIerarchy branch](https://github.com/TiVo/intellij-haxe/releases/download/0.8.1.1.TiVo.ClassHierarchy.11-RC1/intellij-haxe.jar).  It's the active branch right now, though it's not quite stable yet.    If you want to look at the sources, they're at HaxeCommonCompilerUtil.compile() and the setup is at HaxeCommonCompilerUtil.setupOpenFL().

I don't see a way to make the plugin echo the command line it's emitting.  I guess you can always go to the old standby of writing a quick script that dumps its arguments and replace the actual haxelib command with it.

**Comment by RudolfVonKrugstein** [comment]
Ok, this is a little embarrassing. The haxelib executable setting was set to the neko file.
