### ISSUE TITLE
When I build Haxe/Neko project I got errors from compiler marked as information

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#129]
When I build Haxe/Neko project I got errors from compiler marked as information

Steps to reproduce:
Simply try to compile something not valid, and see, that output says there is 1 error and it is shown as information(instead should be marked as error)

TIR: STB-7741

**Comment by EBatTiVo** [comment]
Should be fixed by PR #180.

**Comment by EBatTiVo** [comment]
Fixed.  Will be in the next release after 0.9.3.  Please re-open if it recurs.
