### ISSUE TITLE
Imports: incorrect processing for duplicated imports

### ISSUE THREAD

**Issue by vaukalak** [TiVo/intellij-haxe#132]
suppose code:

```
import somepack.classA;
import somepack.classA;
import somepack.classB;
```

Expected result:

Only second import statement is marked as unused.

Actual result:

Both second and third import statements are marked as unused.

**Comment by vaukalak** [comment]
possible solution: https://github.com/TiVo/intellij-haxe/pull/133

**Comment by EBatTiVo** [comment]
Since #133 has been pulled, I'm going to close this bug.  Please re-open if the error recurs.
