### ISSUE TITLE
[CODE REFORMAT] incorrect reformat for object and array children

### ISSUE THREAD

**Issue by vaukalak** [TiVo/intellij-haxe#134]
suppose you have following code:

```
var arr = [{a:1},{a:2},{a:3}];
```
You could separate it to several lines of code. In this case you expect code like this:

```
var arr = [
    {
        a:1
    },
    {
        a:2
    },
    {
        a:3
    }
];
```
actually after reformat the result is like this:
```
var arr = [
{
a:1
},
{
a:2
},
{
a:3
}
];
```

**Comment by vaukalak** [comment]
possible fix: https://github.com/TiVo/intellij-haxe/pull/135

**Comment by EBatTiVo** [comment]
Since pull request #135 was merged as a fix, closing this bug.  Please re-open if the error recurs.
