### ISSUE TITLE
0.8.1.1.TiVo.4 - IDE is not able to see any file or directorory in project

### ISSUE THREAD

**Issue by zasmarkany** [TiVo/intellij-haxe#139]
All my projects are down. After this update i can only see files in my project root. No dirs. 
*.hx files are not parsed - i see them just like any txt file.

**Comment by EBatTiVo** [comment]
What version of IDEA are you running?  On which OS?

**Comment by zasmarkany** [comment]
OSX 14.0.3

**Comment by jasonsturges** [comment]
My initial run on IntelliJ IDEA 14.0.3 with OS X 10.9.5 is not going well.  Corrupted my modules, and froze.

**Comment by EBatTiVo** [comment]
> OSX 14.0.3

So, you mean IDEA 14.0.3, on Mac OSX?

OK. We haven't brought it forward to 14.  There are some incompatible API changes.  I haven't looked into that yet.

Local testing on Linux, using IDEA 3.1.5 (IU.1286) is not showing the error.

**Comment by sganapavarapu1** [comment]
This version works only with: IDEA 13.1.5 or IDEA 13.1.6 
i.e. from build IU-1286 to build IU-1306

Validated on CentOS-6 (Linux), Ubuntu (Linux), and Mac OS X (Yosemite).

Issue 18 which is about bringing this plugin work with IDEA 14 Open API is already open.
Issue 58 is about one of the features (Flash debugging) not working IDEA 14 - due to issue 18.
Issue 66 complains about the same.

**Comment by sganapavarapu1** [comment]
High level summary:
1.	Downloading & installing latest intellij-haxe.jar from https://github.com/TiVo/intellij-haxe/releases works only with IDEA 13.1.5 or 13.1.6 i.e. from build IU-1286 to IU-1306. It does not work with IDEA 14.x
2.	Downloading & installing latest intellij-haxe.jar from https://plugins.jetbrains.com/plugin/6873?pr=idea or installing it from within the IDEA by selecting the option “Install JetBrains Plugin” – both options do NOT work with either IDEA 13 or 14. 

My environment:
IntelliJ IDEA Ultimate edition 13.1.6 build IU-1306
CentOS 6.5

My hunch, without much investigation… from top of my head:
	There is some version incompatibility and plugin is not recognized (or)
	Haxe SDK type is not compatible… it is not recognized.

**Comment by EBatTiVo** [comment]
> 2. Downloading & installing latest intellij-haxe.jar from https://plugins.jetbrains.com/plugin/6873?pr=idea or installing it from within the IDEA by selecting the option “Install JetBrains Plugin” – both options do NOT work with either IDEA 13 or 14.

As it turns out, they were both built using a JDK higher than 1.6, so if you get the error message "Unsupported major.minor version 51.0", running IDEA on a Java 1.7(?) or later JRE should get you past it.

**Comment by as3boyan** [comment]
0.9 release works fine for me. I got issue with selecting main class - I can't select Main for some reason...

**Comment by sganapavarapu1** [comment]
as3boyan, Thanks for the updated (fixed) version... appreciate it.

v 0.9 works for me.

My environment:
    IntelliJ IDEA Ultimate edition 13.1.6 ... build IU-1306  (running on JDK 1.6.0_41)
    CentOS release 6.6

**Comment by as3boyan** [comment]
>Downloading & installing latest intellij-haxe.jar from https://plugins.jetbrains.com/plugin/6873?pr=idea or installing it from within the IDEA by selecting the option “Install JetBrains Plugin” – both options do NOT work with either IDEA 13 or 14. 

Update: right now it should work for both IDEA 13 and 14

**Comment by zasmarkany** [comment]
Works great now:)
