### ISSUE TITLE
When html or hxml is edited, IDE freezes.

### ISSUE THREAD

**Issue by siratama** [TiVo/intellij-haxe#141]
When the plug-in is uninstalled or it's returned to 0.8.1, it normally functions.

Plugin version: 0.9 or 0.8.1.1.TiVo.4
Windows 8.1
Intellij IDEA 13.1.6

**Comment by as3boyan** [comment]
Plugin attempts to get available compiler arguments and libs once when you type.

We changed process to make it work in JDK 1.7, not sure how it works now, I will test it.

**Comment by ubald** [comment]
With 0.9 and IDEA 14 or 14.1 EAP I also get random freezes. I wasn't able to find a particular pattern for the freezes yet.

**Comment by EBatTiVo** [comment]
@siratama - Are you doing something in particular, or is the crashing random?  Do you have some sample code that we can load?

**Comment by EBatTiVo** [comment]
@ubald - 0.9.**2** is for IDEA 14.  It's a completely separate build from 0.9.

**Comment by siratama** [comment]
A Haxe project is created first. Next when some characters are typed after html file creation, IDE freezes certainly.
Is an error log needed? Which log file should be shown?

**Comment by ubald** [comment]
Yes 0.9.2, and it still freezes every 2 minutes.

**Comment by as3boyan** [comment]
Was able to reproduce it. Plugin waits for `haxelib` process response I think.

**Comment by as3boyan** [comment]
Maybe `haxelib` API changed...

Changed to:
```java
availableHaxelibs = HaxelibClasspathUtils.getAvailableLibrariesMatching(sdk, "\"\"");  // Empty string means all of them.
```

```java
process.waitFor();
```

moved below reading stream

Fixed.

**Comment by as3boyan** [comment]
Release 0.9.2 is out on JetBrains plugin repository with fix for this issue.

**Comment by siratama** [comment]
It didn't freeze any more in 0.9.2. I thank your fix.
