### ISSUE TITLE
text copy not working

### ISSUE THREAD

**Issue by kusamochi** [TiVo/intellij-haxe#145]
thanks for the 0.9.1 update, found the text copy not working.. any hint if I can fix it on my side?

**Comment by EBatTiVo** [comment]
If you are set up to build it for IDEA 14, you are certainly welcome to try:  The suspect is the class HaxeReferenceCopyPasteProcessor, which had a compile issue this morning when we tried building the latest sources for 14.  (CopyPastePostProcessor changed from an interface to a class in the transition between IDEA versions 13 and 14.)

**Comment by kusamochi** [comment]
ok I will take a look, thanks :)

**Comment by as3boyan** [comment]
@EBatTiVo Not sure, will test in IDEA 14

**Comment by as3boyan** [comment]
0.9.1 - is for IDEA 14
0.9 - for IDEA 13

**Comment by as3boyan** [comment]
Copy paste issue fixed. Update is on JetBrains plugin repository. (0.9.2 for IDEA 14)
