### ISSUE TITLE
compiling for both IDEA 13 and IDEA 14

### ISSUE THREAD

**Issue by yanhick** [TiVo/intellij-haxe#150]
@EBatTiVo 
With the Ant task that I use to build the code, I can choose .java file to exclude.
http://ant.apache.org/manual/Tasks/javac.html

So I could exclude files based on wether the build is for 13 or 14. Will it be enough for the automated builds ? I don't know how to do that for builds from intellij though.

**Comment by EBatTiVo** [comment]
OK, so for each incompatible change, we'll have to extract the minimum amount of code into a helper class for each release.(I suggest in a sub-directory under where the class normally goes).  e.g. com/intellij/plugins/haxe/editor/IDEA14/HaxeReferenceCopyPasteProcessor.

So, we'll now have two classes:
- com/intellij/plugins/haxe/editor/IDEA14/HaxeReferenceCopyPasteProcessor.
- com/intellij/plugins/haxe/editor/IDEA13/HaxeReferenceCopyPasteProcessor.

and a helper class that holds common code (if any):
- com/intellij/plugins/haxe/editor/HaxeReferenceCopyPasteProcessorHelper

We still need a way to do a similar thing for src/META-INF/plugin.xml, though I guess we could swap that in at build time.  What we really need is a way to detect which build is running and set a few environment variables, which also, I think, can be substituted into the plugin.xml file.  And, ultimately, as you said, do it from within IDEA as well as well as the external build you're setting up.

**Comment by EBatTiVo** [comment]
> So, we'll now have two classes

Ugh, I forgot that Java is going to add the .IDEA13. and .IDEA14. to the class paths.  Is there a way to suppress that?

**Comment by yanhick** [comment]
Seems like a good plan.

For the .IDEA13. and .IDEA14. classpath issue, I don't know enough about java to know if there are some options in the compiler.
We could copy the right file in com/intellij/plugins/haxe/editor/HaxeReferenceCopyPasteProcessor.java before compiling but this is starting to become messy.

**Comment by as3boyan** [comment]
It's not only HaxeReferenceCopyPasteProcessor, there are few files more(I emailed Eric which ones), I think maybe just simply build different branches, because when I work on IDEA 14 branch, I don't think it's handy to copy this and etc...

If Java has some conditional compilation, like Haxe does

#if IDEA14, then we could maintain single branch I think

**Comment by yanhick** [comment]
Could you submit the whole list here also ? Thanks.

I'd prefer not to have multiple branches if possible as branchs tend to get out-of-sync. It's simpler to have one "single source of thruth" branch for automated testing and releasing.
I guess we could use the C preprocessor for #if IDEA14, altough this doesn't seem to be done much in Java.

I'll look into it, there is probably a common answer in Java for this issue.

**Comment by as3boyan** [comment]
src/com/intellij/plugins/haxe/runner/HaxeRunner.java
src/com/intellij/plugins/haxe/runner/debugger/HaxeDebugRunner.java
src/com/intellij/plugins/haxe/runner/debugger/HaxeFlashDebuggingUtil.java
src/com/intellij/plugins/haxe/editor/HaxeReferenceCopyPasteProcessor.java 
plugin.xml

**Comment by EBatTiVo** [comment]
We've solved this and checked in a whole bunch of changes to implement it.  Everything was complete with change 605785a4cbee4733d21189eba9692c744a9a7477.
