### ISSUE TITLE
parsing problem. can't recognize creating class as a parameter

### ISSUE THREAD

**Issue by codeservice** [TiVo/intellij-haxe#162]
Example:
renderer.render(graphicShape.graphics, null, null, new Rectangle(0,0,data.width,data.height), mw, mh);

renderer.render(graphicShape.graphics, null, null, new Rectangle(0,0,data.width,data.height),<------- unexpected ,

**Comment by EBatTiVo** [comment]
Please provide the version of the plugin, IDEA, Java and OS.

**Comment by codeservice** [comment]
IDEA: 14.0.3
PLUGIN: 0.9.2
OS: Windows 7 (32 bit)
Java:
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode)

**Comment by EBatTiVo** [comment]
Found it:  The new_recovery rule in haxe.bnf needs a comma added.  Should be:
```
private new_recovery ::= !(')' | '}' | ';' | '.' | ',')
```

Test code:
```haxe
package ;

class Test162_a {
}

class Test162 {
    public function tryInstantiating() : Void {
        var qr:Test162_a = new Test162_a();
        resolve( new Test162_a() );
        resolve2( new Test162_a(), new Test162_a());
    }

    public function resolve(qr:Test162_a) : Void {
    }

    public function resolve2(qr: Test162_a, qr2: Test162_a) {

    }
}
```

**Comment by codeservice** [comment]
Yes, looks like comma missing
private new_recovery ::= !(')' | '}' | ';' | '.') to private new_recovery
::= !(')' | '}' | ';' | '.' | ',')

renderer.render(graphicShape.graphics, null, null, new
Rectangle(0,0,data.width,data.height)/*, mw, mh*/); //works if no
comma on current grammar

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/39fb57221093ef52cfd247f41d3fdc3ee45ea6a5

Will be in the next minor drop.
