### ISSUE TITLE
intellij 14 debug conflict

### ISSUE THREAD

**Issue by inagun** [TiVo/intellij-haxe#166]
Hi, i've downloaded the latest version of haxe plugin in intellij 14.0.3, and when i open a play framework 2 project (without any haxe module inside) and run or run with debug it, it's failing

Information:18/03/2015 23:49 - Compilation completed with 2 errors and 0 warnings in 0 sec
Error:No main class for module: root
Error:Compilation failed

removing the plugin fix the issue. it's seems as a conflict.

**Comment by giabao** [comment]
What is your run configuration?
Can you reproduce the isssue with a simple play2 project?

**Comment by inagun** [comment]
I have created a new simple java project with activator, importe it in intellij idea via sbt and configure debugger has play 2 app with default parameters

test with jdk1.8.0_25.jdk or jdk1.7.0_71.jdk
URL http://localhost:9000
debug port 9999
jvm option -Xms512M -Xmx1024M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M

when i run or debug ->
Information:19/03/2015 17:38 - Compilation completed with 2 errors and 0 warnings in 0 sec
Error:No main class for module: root
Error:Compilation failed

if i build/run with activator.
if i remove haxe plugin, it's ok with same parameters

my config
osx yosemite 10.10.2
intellij 14.0.3 on jvm 1.8.0_25
haxe plugin 9.2

below find logs from idea.log

without plugin...
2015-03-19 18:07:20,250 [ 238857]   INFO - ij.compiler.impl.CompileDriver - COMPILATION STARTED (BUILD PROCESS) 
2015-03-19 18:07:20,251 [ 238858]   INFO - j.compiler.server.BuildManager - Using preloaded build process to compile /Users/inagun/Dev/PLAY/simple-test 
2015-03-19 18:07:35,498 [ 254105]   INFO - lij.compiler.impl.CompilerUtil - 	COMPILATION FINISHED (BUILD PROCESS); Errors: 0; warnings: 0 took 15252 ms: 0 min 15sec 

with plugin... 
2015-03-19 18:01:55,135 [1609858]   INFO - ij.compiler.impl.CompileDriver - COMPILATION STARTED (BUILD PROCESS) 

do you need other informations ?

**Comment by EBatTiVo** [comment]
Related to #215?

**Comment by sganapavarapu1** [comment]
yes, this is related to # 215

We see same messages in our Android developer's machines as well.

Error:No main class for module: ...
Error:Compilation failed

**Comment by as3boyan** [comment]
We will need to look at build handler, maybe it needs some check if module is Haxe module...

**Comment by as3boyan** [comment]
Fix for this issue https://github.com/TiVo/intellij-haxe/pull/218

**Comment by EBatTiVo** [comment]
A fix is in place.  @inagun, please re-open if this is not fixed in 0.9.3.
