### ISSUE TITLE
Error:(52, 57) java: interface expected here

### ISSUE THREAD

**Issue by vbence** [TiVo/intellij-haxe#167]
After adding the Ultimate plaftform and Flex I am getting the following error message:

```
/home/bence/tools/intellij-haxe/src/com/intellij/plugins/haxe/editor/HaxeReferenceCopyPasteProcessor.java
Error:(52, 57) java: interface expected here
```

The code involved:
```
public class HaxeReferenceCopyPasteProcessor implements CopyPastePostProcessor  {
```

When I check the class in question:
```
public abstract class CopyPastePostProcessor<T extends TextBlockTransferableData> {
```
it is indeed an abstract class; not an interface.

*Note: I am using the UI-139.1117.1 trial downloadable from the IntelliJ website as the platform, but compiling under Community Edition - I don't think this can be a problem though.*

**Comment by EBatTiVo** [comment]
You are using the code branch for Idea 13 and compiling with Idea 14.  What you are seeing is the result of an incompatible change between the two versions.  The Idea14 code is available in [*masterIdea14* branch on the TiVo fork](https://github.com/tivo/intellij-haxe/tree/masterIdea14).  We are pursuing options to get a unified source base again.  Until that time, we are merging code into both branches.

>  *I am using the UI-139.1117.1 trial downloadable from the IntelliJ website as the platform, but compiling under Community Edition - I don't think this can be a problem though.*

Actually... the plugin uses portions of Idea Ultimate for the navigate->hierarchy and diagram views.  You can probably *build* using community edition using an Ultimate SDK, but you won't successfully *run* the plugin under CE. (At least, not all of the functionality will work.)
