### ISSUE TITLE
"update()" in FlxState are "unresolved symbols"

### ISSUE THREAD

**Issue by giabao** [TiVo/intellij-haxe#168]
see https://groups.google.com/forum/#!msg/haxeflixel/gGmJ_B3x6tQ/Dxltcsvsi7sJ

we can reproduce the bug by open structure view for Bar.hx with the following code:

//file Foo.hx
```
class Foo { }
```

//file Col.hx
```
class Col<T> {
    var iiii: Int;
}
```
//file Bar.hx
```
class Bar extends Col<Foo> {
    var ssss: String;
}
```

Note that, if we put all class in one file then structure view will show Col as super class of Bar but if put each class in one file then structure view (for Bar.hx) will NOT show Col.

**Comment by EBatTiVo** [comment]
Merged.  Closing.  @giabao - Please verify and re-open if this merge was incorrect.
