### ISSUE TITLE
incompatible (can't compile) with IDEA-141.157.3

### ISSUE THREAD

**Issue by giabao** [TiVo/intellij-haxe#170]
error in HaxeStructureViewFactory because:
TreeBasedStructureViewBuilder.createStructureViewModel() is removed in [this commit](https://github.com/JetBrains/intellij-community/commit/f1fa0838a03e3ae3b5f16d74ee99d017f90c8483)

error in HaxeRegularExpressionImpl because:
HaxeRegularExpressionImpl.supportsExtendedHexCharacter  & supportsNamedGroupRefSyntax is added in [this commit](https://github.com/JetBrains/intellij-community/commit/478790592021e30ccf37056175a87b88e173b735) & [this commit](https://github.com/JetBrains/intellij-community/commit/733be82403903d8616366627e3e841ceb84c3c61)

**Comment by EBatTiVo** [comment]
IDEA-141 is 14.1, right?  We haven't gotten Idea 14 solid yet.

Thanks for the report and the research.

**Comment by giabao** [comment]
yes, it is 14.1.
I have maked a PR to branch masterIdea14.
is branch masterIdea14 for IDEA 14.x or just for 14.0?

**Comment by EBatTiVo** [comment]
> is branch masterIdea14 for IDEA 14.x or just for 14.0?

As long as it compiles for 14.0, we can put any 14.x changes there.  If they are 14.1 specific, then we will need to add another branch.  However, is it possible, with the your changes, to keep the old signatures intact, and call the new signatures?  I'm not sure whether we can just drop the @Override on the new functions, but it's worth a try.  At any rate, if we can keep the old signatures, then this change, anyway, can remain 13.x compatible as well.

**Comment by giabao** [comment]
I think you should add another branch for idea 14.1 because:
1. RegExpNamedGroupRef is [added in rev 5d585f5](https://github.com/JetBrains/intellij-community/commits/master/RegExpSupport/src/org/intellij/lang/regexp/psi/RegExpNamedGroupRef.java) which is only included since idea/140.361 (expand & see the tag list of commit [5d585f5](https://github.com/JetBrains/intellij-community/commit/5d585f5) ) (idea 14 is 138.* & 139.* - see [Release Notes](https://confluence.jetbrains.com/display/IDEADEV/IDEA+14+EAP) )
2. since HaxeRegularExpressionImpl implement RegExpLanguageHost, it must implement method supportsNamedGroupRefSyntax(RegExpNamedGroupRef) in all IDEA from idea/140.370+ (see tag list of commit [733be824](https://github.com/JetBrains/intellij-community/commit/733be82403903d8616366627e3e841ceb84c3c61) - this commit is where the method being added)

That means: If we support IDEA 14.1 (idea/140.370+) => must implement RegExpLanguageHost.supportsNamedGroupRefSyntax(RegExpNamedGroupRef) => RegExpNamedGroupRef must existed => IDEA must be idea/140.361+ => can't support IDEA 14.0 in the same code base!
