### ISSUE TITLE
Migration to IntelliJ IDEA 14 API

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#18]
This one is not urgent, it seems like JetBrains works mostly on 14 version and we will have to migrate eventually. It seems like they removed JpsSerialization modules and other jps stuff from API. So it shouldn't be hard to upgrade plugin to work with 14 version. Currently it's in preview, but we might need to consider such possibility in near future.

TIR: STB-2896

**Comment by EBatTiVo** [comment]
Fixed as of 605785a4cbee4733d21189eba9692c744a9a7477.  A masterIdea14 branch was created and kept updated for a while.  Now it has all been merged back to the master branch, which can build any of the following flavors: 13.1, 14, 14.1.
