### ISSUE TITLE
source tree structure to build multiple version

### ISSUE THREAD

**Issue by yanhick** [TiVo/intellij-haxe#186]
I got the ```make``` command to be able to build both 13.1.6 and 14.0.1 with the same branch from the command-line. 
This is in this branch, which is a work in progress:
https://github.com/TiVo/intellij-haxe/tree/build-13-and-14-from-CLI

I had to move the content of the ```src/com``` folder into ```src/common/com``` to make it work. The issue is that if I include the ```src``` folder in the Ant script, then it will always include the content of ```src/13.1.6``` and ```14.0.1```. Instead I now include ```src/common``` as well as ```src/13.1.6``` or ```src/14.0.1``` based on the version I want to build (provided by  some command line argument).

What do you think would be a good folder structure ? 
Also, unrelated, what is the reason for having a separate ```common``` folder at the top level ?

**Comment by yanhick** [comment]
@EBatTiVo

**Comment by EBatTiVo** [comment]
Sorry, Yannick.  I thought I had replied.  Having /src/common/com/... in addition to the version specific trees seems like the proper answer -- at least for the time being.

I don't know why the code at /common/ is not under the main src/ directory.  It is only code that interfaces with the Haxe compiler, though.  Odd.  I don't see why we can't put it in the same directory structure as the main code, though.  Maybe Fedor (@fkorotkov) can shed some light on it?

**Comment by yanhick** [comment]
Thanks, I'll prepare the pull request. I'll move the ```common``` folder in ```src/common``` later in the week if nobody opposes it.

**Comment by EBatTiVo** [comment]
I integrated this and merged it in #237.
