### ISSUE TITLE
debug port left open after application quits

### ISSUE THREAD

**Issue by johngirvin** [TiVo/intellij-haxe#189]
IntelliJ 13.1.6 Ultimate, plugin 0.9.2

When I run a Haxe application from the "debug" button then quit it either from the application itself or using the "stop" (red square) button on IntelliJ, the debug port is left open and I am unable to re-run the application due to a "Address already in use" error. Restarting IntelliJ releases the port.

**Comment by EBatTiVo** [comment]
@johngirvin Why did you close this?  Version mismatch?

I think that plugin 0.9.2 is for IDEA 14.  0.9 is the latest for Idea 13.  But that may be beside the point.
