### ISSUE TITLE
HaxeRemote debugger crashes on connect

### ISSUE THREAD

**Issue by johngirvin** [TiVo/intellij-haxe#190]
IntelliJ 13.1.6 Ultimate, plugin 0.9.2, debugger library from https://github.com/TiVo/debugger

Running a Haxe application from the "debug" button and attaching a HaxeRemote debugger results in a crash.

Crash log: http://pastebin.com/nXKDQuxA

```
/usr/lib/haxe/haxelib run lime run mac -verbose -Ddebug -debug -args -start_debugger -debugger_host=localhost:6972
 ___     
/\_ \    __                       
\//\ \  /\_\    ___ ___      __   
  \ \ \ \/\ \ /' __` __`\  /'__`\ 
   \_\ \_\ \ \/\ \/\ \/\ \/\  __/ 
   /\____\\ \_\ \_\ \_\ \_\ \____\
   \/____/ \/_/\/_/\/_/\/_/\/____/

Lime Command-Line Tools (2.3.0)

Initializing project...
Using project file: /Users/girv/projects/haxe/HelloWorld/project.xml
Reading HXCPP config: /Users/girv/.hxcpp_config.xml
Using target platform: MAC

Running command: RUN
  - Changing directory: export/mac64/cpp/bin/HelloWorld.app/Contents/MacOS
  - Running command: ./HelloWorld -start_debugger -debugger_host=localhost:6972 -livereload
Connected to debugging server at localhost:6972.
```

```
	public static function main():Void
	{
        new debugger.HaxeRemote(false, 'localhost', 6972);
	}
```

TIR: STB-9366

**Comment by EBatTiVo** [comment]
@johngirvin The haxe plugin 0.9.2 was an IDEA v14 compatibililty release and was mismarked; it should not have been installable on 13.  Try using the 0.9.3 release specific to your IDEA version (there are both v13.1 and v14.0 builds).  Version 14 had API differences for the runner, so a correct installation should fix your problem.

Please reopen this bug if the problem exists in a valid configuration.

**Comment by EBatTiVo** [comment]
@johngirvin BTW, the 0.9.3 release is available in the IDEA plugin repository and on our release page https://github.com/TiVo/intellij-haxe/releases.
