### ISSUE TITLE
Import `AS` not supported

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#199]
Since Haxe 3.2 `in` = `as` (in import). 
E.g.: `import any.any.Thing in Foo;` is equal `import any.any.Thing as Foo;`

![screen shot 2015-04-04 at 1 05 15](https://cloud.githubusercontent.com/assets/888526/6989645/cbff2b6e-da66-11e4-8063-deebe0fa273b.png)

http://haxe.org/manual/type-system-import.html#since-haxe-3.2.0

**Comment by as3boyan** [comment]
Ok, see, they added some docs, nice. Seems like we would have to allow both keywords.

**Comment by as3boyan** [comment]
Thanks.

**Comment by fzzr-** [comment]
Thank you!

**Comment by EBatTiVo** [comment]
Looks like @fzzr- recieved and tested the fix.  Closing.  Re-open if it's not fixed or recurs.
