### ISSUE TITLE
Definition when `import in` for found

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#200]
Can't find definition defined using `import in`.

![screen shot 2015-04-04 at 1 04 48](https://cloud.githubusercontent.com/assets/888526/6989688/8419383e-da67-11e4-930d-38d0d839eb81.png)
![screen shot 2015-04-04 at 1 10 57](https://cloud.githubusercontent.com/assets/888526/6989687/84165e02-da67-11e4-929e-01cfc6c4688c.png)

**Comment by fzzr-** [comment]
Works correctly in latest release.

**Comment by EBatTiVo** [comment]
@fzzr- Which release is the 'latest' you are referring to?  0.9.3?  Your own build with sources from when?

We are working on types with parameters right now, and I'd like to figure out what fixed this problem for you.

**Comment by fzzr-** [comment]
I using you build [0.9.3 Community Release](https://github.com/TiVo/intellij-haxe/releases/tag/0.9.3) and no feeling this issue now - all works perfect! If I will found something new - will write here or create a new issue.

**Comment by fzzr-** [comment]
This issue posted when I used Idea 14 Ultimate. Now I using Idea 14 Community Edition.

**Comment by fzzr-** [comment]
Wow, *SORRY!* That comment is my mistake. I messed up an issue. Very sorry!

**Comment by eliasku** [comment]
Looks like fixed in 0.9.9
![image](https://cloud.githubusercontent.com/assets/3038174/13174140/c05a85ca-d712-11e5-92bb-3601e9703684.png)

BTW: `haxe.Constraints.Function` is now imported correctly and you could use just `Function`

@fzzr- please verify in 0.9.9 version

**Comment by EBatTiVo** [comment]
Closing as fixed.  Please re-open if it recurs.
