### ISSUE TITLE
import with keyword in package

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#201]
`import haxe.extern.Rest;`

![screen shot 2015-04-04 at 1 39 03](https://cloud.githubusercontent.com/assets/888526/6989983/a4c39e9a-da6b-11e4-93c3-e53e5f0d9e26.png)
![screen shot 2015-04-04 at 1 39 18](https://cloud.githubusercontent.com/assets/888526/6989985/ae167652-da6b-11e4-8580-365c145fd380.png)
![screen shot 2015-04-04 at 1 39 26](https://cloud.githubusercontent.com/assets/888526/6989986/ae174d5c-da6b-11e4-81d8-d35b5898639d.png)

**Comment by as3boyan** [comment]
classes from Haxe 3.2
http://haxe.org/manual/lf-externs.html#since-haxe-3.2.0

**Comment by as3boyan** [comment]
`package haxe.extern;` Haxe plugin treats `extern` as keyword

**Comment by as3boyan** [comment]
@Simn How to you check if extern is keyword or not? We used `"macro" [\ ]+` in lexer for macro, maybe you have a better idea?

**Comment by eliasku** [comment]
@fzzr- @Simn @as3boyan Looks like fixed... (checked on v0.10.1 rc2 )

![image](https://cloud.githubusercontent.com/assets/3038174/19381370/f47390a2-9203-11e6-86c5-3464650aafc7.png)

@EBatTiVo  let's close that!

**Comment by EBatTiVo** [comment]
OK.  Closing, since @eliasku says it's fixed.
