### ISSUE TITLE
@:remove extern private must be valid

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#202]
Pls add `@:remove extern private` into bnf.
[Example gist: (https://gist.github.com/puffnfresh/5314836#file-valueclass-hx-L6-L7) (not my)](https://gist.github.com/puffnfresh/5314836#file-valueclass-hx-L6-L7)
![screen shot 2015-04-04 at 4 02 59](https://cloud.githubusercontent.com/assets/888526/6990876/0fec8628-da80-11e4-8dd0-66e60ce016db.png)

**Comment by as3boyan** [comment]
Seems like `private` is not expected.

**Comment by as3boyan** [comment]
@Simn maybe just add a bit info on use `private` keywords on classes, I found example here http://old.haxe.org/ref/oop

**Comment by as3boyan** [comment]
It seems like here, we are not expecting other structures than `class`
```
externClassDeclaration ::= macroClassList? externOrPrivate* 'class' componentName genericParam? inheritList? '{' externClassDeclarationBody '}'
{pin=4 mixin="com.intellij.plugins.haxe.lang.psi.impl.AbstractHaxePsiClass" implements="com.intellij.plugins.haxe.lang.psi.HaxeClass"}
```

**Comment by Simn** [comment]
Not sure what you want to know. You can have any number of metadata and then optionally `private` or  (not xor) `extern` in any order. That's true for both `class` and `interface`.

**Comment by as3boyan** [comment]
I added `interface` to extern classes, and I thought that maybe I was missing something else. I think now plugin works in a same way as you mentioned. Thanks for info.

**Comment by EBatTiVo** [comment]
We've got a merged fix.  Closing.  @fzzr- Please test and re-open if the bug recurs.
