### ISSUE TITLE
Uncomment feature broken for block comments.

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#209]
Uncommenting for multiline comments now not works.

Haxe plugin now:
![uncomment-haxe mov opt](https://cloud.githubusercontent.com/assets/888526/6993300/a6334b30-daf8-11e4-85f1-9aee8c3a31d5.gif)

Need (Flash) :
![uncomment-flash mov opt](https://cloud.githubusercontent.com/assets/888526/6993265/e9153a86-daf7-11e4-80d6-6a2555bf5270.gif)

TIR: STB-9371

**Comment by fzzr-** [comment]
Works correctly in latest release.

**Comment by EBatTiVo** [comment]
Since it's working, I'm going to close this.
