### ISSUE TITLE
Java tests won't start for Java project(plugin) when Haxe plugin is enabled

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#215]
Java tests won't start for Java project(plugin) when Haxe plugin is enabled

IDEA 13.1.6
Project - Haxe plugin

If I enable Haxe plugin, then when I try to run tests on Java project(plugin) I got this error:
`no main class`

**Comment by EBatTiVo** [comment]
This is weird.  This is either the second or third case where we have issues with other language plugins when Haxe is installed.  I wonder if the Haxe plugin is installing/registering one of it's subclasses as a (mismarked?) subsystem for the Java language, and is thus overriding the standard Java behavior.  Or, more likely, that one of the Java classes that are sub-classed (re-used) by the Haxe plugin does this normally, and is now actually installing the sub-class when it thinks it is installing itself.

```git bisect``` can probably help us here, but it's going to be tedious uninstalling and re-installing the plugin every time we want to test.

Have you noticed whether the issue occurs when we are debugging the Haxe plugin (e.g. debugging or running a secondary instance in the plugin playground), or only when the plugin is installed normally in a primary instance?

**Comment by as3boyan** [comment]
primary instance, not sure about secondary

**Comment by sganapavarapu1** [comment]
This turned out to be a blocker at TiVo for Android team.

One of the Android developers came to my cube just now and complained that - 
They are compelled to upgrade to IJ IDEA 14 for other reason - they use multi-dexing which needs this upgrade. So, they upgrade IDEA to 14 - now, they need to get latest Haxe plugin (0.9.2) for functional Haxe plugin. Once they install this latest plugin - it  is blocking all kinds of builds... gradle, Java / Android etc.

They need this fixed rather urgently - needs to be escalated because entire Android development team is  blocked.

**Comment by kaushikprajapati** [comment]
Srikanth described the situation and so I will get to the business of how to produce this issue and add more details.

IntelliJ Version: 14.1.1 Build #IU-141.178
Haxe Plugin: 0.9.2

Please use below google drive link to get sample project, my idea logs and the list of plugins I have installed.

https://drive.google.com/folderview?id=0B5MqYzzaFCjUfmhqMXNPQTNOeXl6ak1Ga0IwSHN0eExyV1pDTWltVFJoSjlNdUJyMGQzeFk&usp=sharing

Steps to produce:

1) Import the sample project (which is sample Android gradle project)
2) Hit the little green play button to build

Error Logs from above steps:

Information:4/8/15, 1:34 PM - Compilation completed with 2 errors and 0 warnings in 19ms
Error:No main class for module: app
Error:Compilation failed

LMK if I can provide any more information.

**Comment by as3boyan** [comment]
Fix for this issue https://github.com/TiVo/intellij-haxe/pull/218

**Comment by as3boyan** [comment]
Same thing for secondary instance, used to happen all the time.

**Comment by EBatTiVo** [comment]
Boyan fixed this a couple of days ago.  It is in the 0.9.3 release.  fede5889b55f68e9ac54cfc1e9a651d045ee405e
