### ISSUE TITLE
Double compilation on lime project

### ISSUE THREAD

**Issue by profelis** [TiVo/intellij-haxe#220]
Now lime project compile two times. First time on build

```haxelib run lime build ...```

and second time when project run

```haxelib run lime test ...```

Maybe you can only run in second time ```haxelib run lime run test...```?

**Comment by EBatTiVo** [comment]
I presume that you are running the build (or make) command, and following it with the run command.  This usually happens as a consequence of your project setup: the standard Run and Debug configurations have a prerequisite 'Make' command in the 'Before launch' section of the dialog.  If you don't want that, remove the 'Make' from that section of the configuration.

If I've misunderstood, please re-open the bug and provide details of your configuration (e.g. IDEA version, plugin version, OS, etc.)
