### ISSUE TITLE
Compiler based auto-complete performance problems

### ISSUE THREAD

**Issue by grisevg** [TiVo/intellij-haxe#230]
Reproduced on Plugin version: 0.9.3 release
Reproduced on IDEA Versions: 13.1.6 and 14.1.1
Reproduced on OS: Win 8.1 x64

Problem: 
Idea freezes for number of seconds when attempting to do any auto-complete even on medium size projects.

Expected: 
Idea should not freezes, auto-complete suggestions should be nearly instant as it was in older version of intellij-haxe plugin (pre-ClassHierarchy).

Ways to reproduce: 
This really depends on a size of the project. Mine is ~100 classes in size and uses "actuate" and "openfl" and "tink_core" haxelibs and it causes idea to freeze for 3-5 seconds on every single auto-complete (which happens just as you type).
If you open tiny OpenFL example projects, intellij-haxe plugin gives good performance.

UPDATE:
This is caused by compiler based auto-complete which is enabled at the moment for OpenFL projects. Temporary solution - switch to different project type (NMML seems to work).

TIR: STB-9402

**Comment by EBatTiVo** [comment]
First guess is that completion is running in the AWT thread and needs to be made to run in the background thread.  With OpenFL, we are actually running the Haxe compiler to get completions, so the speed of getting useful results is dependent upon the compiler speed. (As your projects grow, the compilation speed slows.)  I think we need a checkbox to allow/disallow this functionality, if only for testing purposes.

**Comment by grisevg** [comment]
Hey it worked! So solution for now is to switch to different type of project (NMML worked) which gives good performance.

I believe FlashDevelop solves that by having cache instead of asking compiler for completion every time.

Thank you for temporary solution.

**Comment by profelis** [comment]
@EBatTiVo with Haxe compiler completion you must use compilation Haxe cache server http://old.haxe.org/manual/completion#compilation-cache-server . And checkbox too )

**Comment by EBatTiVo** [comment]
Thanks for the tip.

**Comment by profelis** [comment]
btw, FD has 3 behaviours, auto completion only from FD parser, only from Haxe compiler or merged first two lists.

**Comment by as3boyan** [comment]
It become more tricky when in comes to OpenFL, perhaps we could cache `openfl display` output, for example get it first time, then cache, still needs to watch config changes(targets), perhaps we could cache it for each target, may be better.

**Comment by profelis** [comment]
@as3boyan for the first time add checkbox to on/off haxe compiler completion. Please )

**Comment by as3boyan** [comment]
To the project options?

**Comment by EBatTiVo** [comment]
See additional discussion on #243.

**Comment by as3boyan** [comment]
#251

**Comment by EBatTiVo** [comment]
@grisevg @as3boyan - Looks like Boyan fixed this ten months ago by caching the results of a compile.  Was that a satisfactory fix?  If not, then please re-open.

@RudolfVonKrugstein - I had duped your bug #243 to this one.  Do you agree that your bug was fixed?  If not, then please re-open this one.

**Comment by RudolfVonKrugstein** [comment]
@EBatTiVo the bug was fixed at the time of closing #243. If it is still fixed, I do not know because I haven't used intellij in the last months.
