### ISSUE TITLE
Definition occurrence is not highlighted when usage is clicked

### ISSUE THREAD

**Issue by grisevg** [TiVo/intellij-haxe#235]
Plugin version: 0.9.3
IDEA: 14.1.1
OS: Win 8.1 x64

If you click variable usage, it highlights all the other usages but doesn't highlight the definition:
![image](https://cloud.githubusercontent.com/assets/155348/7161827/0607d272-e389-11e4-94f6-8cae647ce64a.png)
![image](https://cloud.githubusercontent.com/assets/155348/7161833/10f81a8e-e389-11e4-9724-932e56f08203.png)
But if you click on definition, it highlights all usages just fine:
![image](https://cloud.githubusercontent.com/assets/155348/7161877/50b2419a-e389-11e4-8911-4571a0423dcd.png)
![image](https://cloud.githubusercontent.com/assets/155348/7161886/5be514d4-e389-11e4-8ad6-e9cdbacad479.png)

**Comment by EBatTiVo** [comment]
Related to #136

**Comment by eliasku** [comment]
+1, subscribed to

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/76100b443316a2d147f87a3d3caac50a0d909559

This will be included in release 0.9.10.  Please re-open if it recurs.
