### ISSUE TITLE
No auto-completion for static methods

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#262]
Auto-completion is not working for classes with static methods, actually is resolved when you finish typing method call, but while typing it resolves only static properties and fields, but no static methods are showing up. Big slow-down on productivity for new client-code users.

repro:
```
class StaticMethods {
	public static function foo() {}
}

class Main {
	public static function main() {
		//StaticMethods.foo(); // after typing is resolved, this is good
                StaticMethods. // while typing class not resolved (strange behavior)
	}
}
```

![image](https://cloud.githubusercontent.com/assets/3038174/7582768/7d896552-f899-11e4-9143-08990ea2d524.png)

**Comment by profelis** [comment]
same problem in idea 14.1.
