### ISSUE TITLE
Can not parse `return` value with type = a typedef struct

### ISSUE THREAD

**Issue by giabao** [TiVo/intellij-haxe#278]
![return-typedef](https://cloud.githubusercontent.com/assets/1702709/7809332/8e4b6324-03c3-11e5-8dbb-149e809c45b7.jpg)

**Comment by EBatTiVo** [comment]
PR #280

**Comment by EBatTiVo** [comment]
PR #280 has been merged.  Closing.  BTW, this did NOT make the 0.9.4 release.
