### ISSUE TITLE
Completion for 'using' must use the fully qualified name.

### ISSUE THREAD

**Issue by soywiz** [TiVo/intellij-haxe#286]
When adding a "using" the IDE is auto completing with the class name and adding an import.
Instead it should add the fqname after the using.

So instead:

```
import com.test.TestTools;
using TestTools;
```

it should be:

```
using com.test.TestTools;
```

**Comment by EBatTiVo** [comment]
Why is your requested behavior any more correct than the current behavior?  Is there any substantial difference in functionality?

**Comment by soywiz** [comment]
It doesnt work. Haxe compiler doesn't find the using without the fully qualified name. StringTools for example works because the fq is the same as the class name.

**Comment by EBatTiVo** [comment]
The two files that would be involved in this are:
/sandbox/github/tivo/intellij-haxe/src/common/com/intellij/plugins/haxe/ide/HaxeClassNameCompletionContributor.java
/sandbox/github/tivo/intellij-haxe/src/common/com/intellij/plugins/haxe/ide/HaxeCompilerCompletionContributor.java

**Comment by as3boyan** [comment]
You right, I think it's HaxeClassNameCompletionContributor.java, there should be insertHandler, which should call something like addImport which shouldn't add additional import it for using statements.

I can't remember if I added such handler for HaxeCompilerCompletionContributor.java

**Comment by eliasku** [comment]
+1 subscribe

**Comment by eliasku** [comment]
@soywiz 
![feb 25 2016 13 46](https://cloud.githubusercontent.com/assets/3038174/13317468/5a12aed8-dbc6-11e5-9756-0863c6d3bab4.gif)

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/bf0554eb1c337537f51da7b1e96a4adaf439810c

This will be in the 0.9.10 release.  Please reopen if it recurs.
