### ISSUE TITLE
Check override + implement method signature

### ISSUE THREAD

**Issue by soywiz** [TiVo/intellij-haxe#308]
Semantic annotator is just reporting errors when you are overriding a method that is not part of the ancestor classes.

We should check that when overriding the signature of the method is compatible, so in the case you change one method you will get feedback about others being outdated.

I will implement this and will make a PR.

**Comment by EBatTiVo** [comment]
@soywiz   Carlos, did PR #309 fix everything you expected to fix for this issue?  Can we close this?

**Comment by soywiz** [comment]
Sure
