### ISSUE TITLE
Fix testGetterSetter1 test to work in both openjdk + oracle jdk

### ISSUE THREAD

**Issue by soywiz** [TiVo/intellij-haxe#310]
I suspect this is an implementation difference with HashMap. It is used as if the HashMap should return have a consisten behaviour.

In: ```HaxeGenerateAccessorHandler.collectCandidates``` it calls: ```HaxeResolveUtil.namedComponentToMap(subComponents)```

which returns a Map (with a HashMap implementation). Later it uses: ```componentMap.keySet()```which seems to be returning things in any order.

namedComponentToMap could return a LinkedHashMap or, HaxeGenerateAccessorHandler order that set by name.

**Comment by eliasku** [comment]
We had the same issue for jdk1.6 vs jdk1.8.
Our issue has beed fixed. Could you verify `openjdk` / `jdk` problem?
Thanks in advance.

**Comment by EBatTiVo** [comment]
Fixed.  Indeed, the problem was the HashMap returning values in a different order.  (Really, the problem was a change in the hash value implementation.)  Now, we're sorting the generated files to get a consistent ordering.
