### ISSUE TITLE
Modifications to the /gen/ tree have to be reverted and non-generated functions must be integrated differently.

### ISSUE THREAD

**Issue by EBatTiVo** [TiVo/intellij-haxe#323]
Changes 1f7684ee931708f59567fbb48f1fc421e848986d, 1f7684ee931708f59567fbb48f1fc421e848986d, and 1f7684ee931708f59567fbb48f1fc421e848986d introduced manual changes to the generated parser files.  These need to be reverted and the new code added, either to a mixin super-class or using another mechanism.

Primarily the functions that need to be removed are the getModel() methods added for semantic annotation.

TIR: STB-11374

**Comment by EBatTiVo** [comment]
This issue is getting in the way of fixing #316 correctly.

**Comment by soywiz** [comment]
Maybe we can create a static method inside the model. fromElement and something like that. We can create the model each time or store the linked model reference in the userData.

**Comment by EBatTiVo** [comment]
The mixin class isn't hard, and it makes more sense, I think.  That way we don't have to create another set of static utilities.  I rather like being able to request the model from a PSI element.  Both ways will work, though.

Another thought is to add getModel at the PSI layer:  Wrap JavaPsiCodeElement with a HaxeElement type, and add a templatized getModel to it.

**Comment by EBatTiVo** [comment]
PR #330.

I was writing a HaxeFieldModel.fromPsi() method and realized it was just a static call to the constructor, so I used that directly.  Carlos, you can change it to match your other models if you want.  This just gets us past not being able to regenerate the parser code.

**Comment by EBatTiVo** [comment]
Fixed for now.

@soywiz - Carlos, I took the easy way out for the PR.  If you want me to put a couple of mixins in place to get a more consistent API, let me know.  The idea of adding a getModel to all PsiElements seems difficult to do consistently at very generic super-classes given that model construction should return a specific type, so I've abandoned that idea for the moment.
