### ISSUE TITLE
Stack frame does not include fields from "this" when debugging.

### ISSUE THREAD

**Issue by EBatTiVo** [TiVo/intellij-haxe#325]
When debugging, there is a race condition (particularly with IDEA 14, which introduces "auto-expanding") where the variable lists are calculated and drawn before the data is available from the debugger.  This occurs more frequently with large projects.  The "this" pointer is particularly vulnerable to the error.

IDEA 14, 14.1
Plugin versions 0.9.3, 0.9.4..
JDK 1.6
OS: Linux

TIR: STB-10938

**Comment by EBatTiVo** [comment]
The basic problem was that the debug UI's variable tree was being updated and drawn before the variable data was available from the debugger.  Once the data was available, notification and redraw was occurring, but the new elements were not being added to the tree prior to redrawing.

PR #326 fixes this.

**Comment by EBatTiVo** [comment]
Merged #326.

**Comment by bji** [comment]
Yeah on closer inspection, this change is problematic.  It will cause every field of every variable to be fetched, recursively, whenever a breakpoint is hit.  I think this change should be backed out.

**Comment by EBatTiVo** [comment]
Not quite.  I have another version that's working -- and doesn't get all of the variables recursively.  I'll push it soon.

**Comment by EBatTiVo** [comment]
Fixed and merged a while back.
