### ISSUE TITLE
Compile parsing error in latest plugin build + latest openfl/lime

### ISSUE THREAD

**Issue by rickms** [TiVo/intellij-haxe#33]
Using the latest plugin build (https://github.com/JetBrains/intellij-haxe/blob/master/intellij-haxe.jar?raw=true) in conjunction with the latest OpenFL (2.1) and lime (2.0-alpha) results in "blank errors".  

> /
> Error:
> /Users/rickDocuments/GameProjects/haxe/test
> Error:

When manually running  via 

`lime test neko` or  `lime build neko`

There are no actual compile errors.

**Comment by EBatTiVo** [comment]
My notes show that this was fixed in the ClassHierarchy branch a while back.  Should be fixed in master now that everything has been merged.
