### ISSUE TITLE
Obscure behaviour with untyped argument in function

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#336]
[Release 0.9.5](https://github.com/TiVo/intellij-haxe/releases/tag/0.9.5) on Idea 14 Community Edition (14.1.4)

![haxe-plugin-bug-untyped-argument mov](https://cloud.githubusercontent.com/assets/888526/8762150/32fc90c6-2d79-11e5-90fd-70edefb93057.gif)

First item in the autocomplete-list must be "answer". But we see an "answerIsString" like a name of function.

**Comment by profelis** [comment]
Plugin stopped autocomplete function params. All params, not only untyped.

**Comment by EBatTiVo** [comment]
@soywiz - Carlos, I didn't tweak completion, so I have a feeling this is in your changes.  Have any ideas?

@fzzr- If you select the first line of the dropdown, is the insertion working as expected, just not printing the proper text on the first line of the completion dropdown?  (That's what it appears is happening in your animation.)

**Comment by as3boyan** [comment]
This code causes weird IDE errors in 14.1.6 -> I can't select that "answerIsString" function in PsiViewer

15.0.4 also:

![](http://i.imgur.com/DH51xo0.png)

**Comment by as3boyan** [comment]
Probably "presentableText" is wrong for these items

"HaxeLocalVarDeclaration" is not considered in HaxeFieldModel I think

**Comment by bynuff** [comment]
@fzzr- fixed in #456 PR. Update to latest haxe plugin. @EBatTiVo think we can close this issue.

**Comment by EBatTiVo** [comment]
Fixed per @bynuff.  Closing.
