### ISSUE TITLE
Quick start guides needed

### ISSUE THREAD

**Issue by andyli** [TiVo/intellij-haxe#339]
People told me that there is missing a quick start guide on setting up an environment for a Haxe hello world project. And I think it is true. Even I know Haxe pretty well, I'm a new comer to intelliJ and find it difficult to setup.

I would like to contribute some docs on this. Where they should be put? I prefer a markdown file in the repo, such that I can send a PR for you to review and discuss. Will that work?

Btw, is this the repo people should submit issue reports, or contributing to, instead of the one over https://github.com/JetBrains/intellij-haxe?

**Comment by EBatTiVo** [comment]
The README.md file already has a (very) short section on installation of this plugin. To add documentation, you can either edit that file or add a markdown file to the root of the project (such as QUICKSTART.md).  If you use a secondary file, you should also add a link to it from the README.md.

If you're talking about an IntelliJ-focused setup of  the plugin and Haxe from the ground up, then I'm OK with a document that shows how to get that working.  If you're talking about generic Haxe documentation that has little to do with IntelliJ, then that would be better handled via the Haxe Foundation repositories -- you can always add a pointer to them in our README.

If you are planning on adding extensive documentation, or files with drawings, screenshots, and the like, then you may certainly make a doc/ and doc/images/ directory and place your files in there.  I wouldn't move the standard github doc files there, though (README.md, CONTRIBUTING.md, CONTRIBUTORS.md, LICENSE.txt).  They should be left in the root of the tree.

And, yes, this (http://github.com/tivo/intellij-haxe) is the repo for submitting errors and issues.  The JetBrains github repo is managed by JetBrains.  While we send pull requests there (and one of the Haxe Foundation's contractors can merge them), they have stopped development of the Haxe plugin (thus, paying attention to issues submitted on that repo).
