### ISSUE TITLE
Typedef Extensions

### ISSUE THREAD

**Issue by impaler** [TiVo/intellij-haxe#353]
[Typedef Extensions](http://haxe.org/manual/type-system-extensions.html) do not resolve properly and give a "Not a class" error.
You will see them used often in Javascript externs, it makes certain parts of the official hxnodejs break:

https://github.com/HaxeFoundation/hxnodejs/blob/871614b85586d2327df3a307f9ef7bb14c8b8281/src/js/node/ChildProcess.hx#L60

 Eg:

<img width="681" alt="screen shot 2015-09-24 at 8 41 19 pm" src="https://cloud.githubusercontent.com/assets/510807/10071384/c774a0b4-62fc-11e5-8b59-7cd4c0f2ea2b.png">

Using Haxe plugin 0.9.6 with Idea 14.1.3.

**Comment by eliasku** [comment]
PR: https://github.com/TiVo/intellij-haxe/pull/395

**Comment by EBatTiVo** [comment]
@impaler This issue is fixed.  Please test the 0.9.9 release (will be released by Tuesday 9/Feb/16) and re-open if the bug recurs.
