### ISSUE TITLE
Unresolved symbol issues

### ISSUE THREAD

**Issue by elsassph** [TiVo/intellij-haxe#358]
Here's a snippet:

    var doc = js.Browser.document;
    var view = doc.createDivElement();
    view.className = 'view';

In this snippet, `createDivElement` and `className` are hinted as unresolved (underline+tip).

Strangely, you do (sometimes) get code completion for `createDivElement` after `var view = doc.`, but not if you just start the line with `doc.`. 

Importing `DivElement` doesn't help.

PS: IDEA 14.1.4, Haxe 3.2, module configured as HXML / JS target / build.hxml

**Comment by eliasku** [comment]
Please verify, looks like fixed in 0.9.9
![image](https://cloud.githubusercontent.com/assets/3038174/13173386/37d8a2da-d70e-11e5-8915-d6fe7628617c.png)

**Comment by EBatTiVo** [comment]
@elsassph: Phillippe, we think we fixed this in the last release.  Please re-open if you disagree.
