### ISSUE TITLE
Parser doesn't recover after new A|

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#37]
Another issue that @profelis reported earlier:
```haxe
package ;
class Main {
    public function new() {
    }

    private static function main():Void {
        trace("hello world");

        var s = "";
        var d = Date.now();
        trace(d);

        test();

        new RT|
    }

    static public function test() {

    }
}

class RTask {
    public var a:Int;

    public function new() {

    }

}
```

The problem is that parser chokes on `new A|` and it should recover after it somehow, but it doesn't, so all data below this new expression statement doesn't get parsed properly.

TIR: STB-7293

**Comment by EBatTiVo** [comment]
This is fixed in the ClassHierarchy branch, though it's not worth creating a release just for it.  If you want to test within the next week, then you can build from source.  763d87f and 1bfef9d

**Comment by sganapavarapu1** [comment]
verified the fix on ClassHierarchy branch
