### ISSUE TITLE
can't open: Open Module Settings, Project Structure idea 15.0.2

### ISSUE THREAD

**Issue by Seb-AS** [TiVo/intellij-haxe#380]
with the plugin installed I can't open:

Project Structure
Open Module Settings

Idea 15.0.2

works fine with Idea 14.1.4

**Comment by bynuff** [comment]
the same problem in Idea 15.0.2

**Comment by bynuff** [comment]
I had the same problem

**Comment by eliasku** [comment]
+1

**Comment by anibyl** [comment]
+1

**Comment by Liryk** [comment]
+1

**Comment by g4r37h** [comment]
+1

**Comment by nickmain** [comment]
+1

**Comment by sganapavarapu1** [comment]
I know EBatTiVo is currently working on it... you will see a release with IDEA v15 support soon.

**Comment by EBatTiVo** [comment]
This is working for me in the v15Build branch.  Brave souls who like to build this product may want to try that.  Otherwise, I'm actively working on a v15 release now.

**Comment by EBatTiVo** [comment]
Fixed in PR #386: a3bb4b3dd51a71230faf9d44268ac53ff7f9dc6f
