### ISSUE TITLE
Wrong package while parsing library files

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#387]
![image](https://cloud.githubusercontent.com/assets/3038174/12574862/bff5e348-c418-11e5-97e4-40fc1d45421e.png)

If I add library from haxelib, it says that package must be `usr.lib.haxe.lib.format.3,3,2.format.abc`. Looks like class path resolved from file system root. 

Version: 0.9.7 for 14.1.4

**Comment by anibyl** [comment]
+1

**Comment by bynuff** [comment]
+1

**Comment by eliasku** [comment]
Please check PR https://github.com/TiVo/intellij-haxe/pull/389

**Comment by EBatTiVo** [comment]
@eliasku - I merged the PR.  Would you like to add some unit tests?  It would be a help.

**Comment by eliasku** [comment]
Fixed for v0.9.9
