### ISSUE TITLE
No base fields completion for extended anonymous type

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#408]
When use AnonType type extended from AnonBase, fields from base types are not resolved. There are no variants for completion.

Version: next 0.9.9, OSX, IntelliJ IDEA 14.1 / 15

Repro:
```
typedef AnonBase = {
    pack:Int,
    ex:Int
}

typedef AnonExample = {
    >AnonBase,
    params:Int
}

class AnonymousTest {
    public function test(anon:AnonExample) {
        //anon.<caret> - NO VARIANTS for AnonBase
        anon.params;// - OK
    }
}
```

**Comment by EBatTiVo** [comment]
Merged PR #409: f994da794389e0546c4ed9e0c307a0c9f151878e
