### ISSUE TITLE
Can't find method for getter/setter in interface declaration

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#411]
We shouldn't annotate error if get/set-method is not declared for property definition in interface.
![image](https://cloud.githubusercontent.com/assets/3038174/12943371/dec561d8-cff1-11e5-849b-4e8146d8ff66.png)

Repro:
```
interface IBar {
    var value(get, set):Int;
}
```
Version: 0.9.8, 0.9.9
Environment: OSX, IntelliJ IDEA 15

**Possible solution:**
`HaxeSemanticAnnotator.java`
`FieldChecker::checkProperty`
add `!field.getDeclaringClass().isInterface()` condition for GET/SET checking

**Comment by eliasku** [comment]
Looks like fix is already here - https://github.com/TiVo/intellij-haxe/pull/322

**Comment by eliasku** [comment]
But looks like we need to wait too long to merge @soywiz pull request. 
The actual fix is one line of code. I suggest making hot-fix soon as possible and add issue-related unit-test. Hot-fix will be very appreciated by all our team members.
@EBatTiVo What do you think?

**Comment by EBatTiVo** [comment]
@eliasku I am OK taking the changes piecemeal if it won't make Carlos' work a lot harder.
@soywiz Do you have an opinion here?

If you guys want to help and review and test Carlos' code, then maybe we can get it in place sooner rather than later.

**Comment by anibyl** [comment]
+1

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/80ec11b02a586042a782485d9c74c4fc243253d4
