### ISSUE TITLE
Incompatible inherited type in field initializer

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#412]
Annotation is not support inherited Types. Now we had a lot of errors from "annotator" when we initialize base type field in place.

Example:
![image](https://cloud.githubusercontent.com/assets/3038174/12945402/355ab46a-cffe-11e5-8169-31598ff1d729.png)

Repro:
```
interface IBase {}
class Base implements IBase {}
class Base2 extends Base {}

class Test {
    var a1:IBase = new Base();
    var a2:IBase = new Base2();
    var a3:Base = new Base2();

    // workaround
    static var B:Base2 = new Base2();
    var b:IBase = B;
}
```

Version: 0.9.8, 0.9.9
Environment: OSX 10.9, IntelliJ IDEA 15

**Possible solution**:
Investigate and add support for basic inherited types in `HaxeTypeCompatible::canAssignToFromType`

**Comment by EBatTiVo** [comment]
So, we've got a large (>5000 line) pull request from @soywiz that is likely to address this error and some others like it.  He was primarily focused on getting the annotators correct, I had a few comments and we never finished the review.  I was planning on pulling those changes locally and wading through them, but it's one of those things where other pressing issues take precedence.  If you want to give it a go, you may be happily surprised by what he's provided.

**Comment by eliasku** [comment]
Unfortunately fix is not found in @soywiz PR :(

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/1c71a806dc3b06a864468ceee74afab981384ebc
