### ISSUE TITLE
[Project View] One-type-file should be deleted in one operation, now need to delete twice

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#424]
When you have general file with the same name as a class name. IDE shows it for you as a class. You have to delete it twice, first one for class, second for file and other text like imports and package statements.

Repro:
- make Test.hx and print package, imports and `Test` class 
- close and open folder with file to update Test structure in Project View browser
- delete Test from Project View, (right click on Test, chose delete).

Result: you have just Test.hx file now.
Expect: All file will be deleted in one operation (if class name equals file name, and there is only one file)

Version 0.9.9, IDEA 14 / 15, OSX

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/a22bb54943581574673073384468e48ea1b4d473
