### ISSUE TITLE
findUsages output view filters not working as expected

### ISSUE THREAD

**Issue by sganapavarapu1** [TiVo/intellij-haxe#426]
FindUsages output window has filters on its left menu as shortcut icons. These filters, when working (e.g. for Java code), allow you to hide import statement occurrences or interface occurrences etc. Various filters are available for various purposes.

Haxe plugin's findUsage output doesn't seem to be filterable.
At least, I couldn't filter "import " statement occurrences. I didn't test all others, but another filter icon was also not effective.

See attached screen capture

![idea](https://cloud.githubusercontent.com/assets/4454625/13213650/409e5f3e-d8ff-11e5-9ce5-89cf5e0acb51.png)

**Comment by eliasku** [comment]
@sganapavarapu1 It was not implemented before

PR #446
![importfiltering](https://cloud.githubusercontent.com/assets/3038174/13424695/659b4882-dfb3-11e5-926f-deb8506b2f85.gif)

**Comment by EBatTiVo** [comment]
@sganapavarapu1 Please close this after you've verified it.

**Comment by EBatTiVo** [comment]
@sganapavarapu1 Strike that.  I'll just close it pre-emptively.  Re-open if it recurs.

**Comment by eliasku** [comment]
@sganapavarapu1 @EBatTiVo 
This ticket is created about general filters support. We've fixed only **import filter** support. Grouping is not implemented, read/write is also works weird way. But I suggest to close this one and create more descriptive and specific issues for the remaining support (grouping and read/write filters) to make tasks more clear for contributors.

**Comment by sganapavarapu1** [comment]
@eliasku 
I agree. Though my intent was to open the ticket only for import filter (as I thought that's small enough to achieve), I ended up making title cover broader scope. Yes, making smaller tickets encourages contributions, easier to review/merge and manage overall in remote working conditions.
