### ISSUE TITLE
[AbstractEnum] No field completion

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#427]
There is no completion for `@:enum abstract` fields.
![image](https://cloud.githubusercontent.com/assets/3038174/13221240/6e775ffa-d98b-11e5-8953-833481bf9fe2.png)
Repro:
```
@:enum abstract AbstractEnum(Int) from Int to Int {
    var ONE = 0;
    var TWO = 1;
}

class AbstractEnumFieldCompletion {
    public function new() {
        AbstractEnum.ONE; // field resolved
        AbstractEnum. // no completion variants
    }
}
```
Version: 0.9.9, IDEA 14/15, OSX

**Comment by as3boyan** [comment]
Haxe compiler should provide this, but it may be limited to HaxeReferenceExpressions

**Comment by eliasku** [comment]
We should support it well at the semantic model level, as `@:enum` is a part of the language now

**Comment by anibyl** [comment]
+1

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/451219ae74db794af4f005f5d93fe17769ddb47d
