### ISSUE TITLE
[AbstractEnum] Field type not resolved

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#428]
`@:enum abstract` fields type not resolved.
![image](https://cloud.githubusercontent.com/assets/3038174/13221294/c4b234bc-d98b-11e5-89d6-d4c147687f1a.png)
```
@:enum abstract AbstractEnum(Int) from Int to Int {
    var NONE = 0;
    public function foo():Void {}
}

class ResolveAbstractEnumFieldType {
    public function new() {
        var a:AbstractEnum = AbstractEnum.NONE;
        a.foo(); // ok

        var b = AbstractEnum.NONE;
        b.foo(); // UNRESOLVED
    }
}
```
Version: 0.9.9, IDEA 14/15, OSX

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/451219ae74db794af4f005f5d93fe17769ddb47d

**Comment by olinkirkland** [comment]
I'm having this problem in 1.2. I'm using Haxe 3.4.4.
