### ISSUE TITLE
[AbstractEnum] Parameter default value must be constant

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#429]
For `@:enum abstract` types very common to provide default values with one of fields, such as `function foo(a:PlayerMode = PlayerMode.DEFAULT)`. But now annotator can't resolve that `@:enum abstract` fields is already constants.
![image](https://cloud.githubusercontent.com/assets/3038174/13221358/1c1035a6-d98c-11e5-9e95-cba6e50d93ea.png)
Repro:
```
@:enum abstract AbstractEnum(Int) from Int to Int {
    var ONE = 0;
    var TWO = 1;
}

class AbstractEnumParameterDefaultValue {
    public function foo1(type = AbstractEnum.ONE) {}
    public function foo2(type:AbstractEnum = AbstractEnum.ONE) {}
    public function foo3(type:Int = AbstractEnum.ONE) {}
    public function foo4(type:Dynamic = AbstractEnum.ONE) {}
}
```
Version: 0.9.9, IDEA 14/15, OSX

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/451219ae74db794af4f005f5d93fe17769ddb47d
