### ISSUE TITLE
Variable redefinition

### ISSUE THREAD

**Issue by anibyl** [TiVo/intellij-haxe#431]
Plugin doesn't show invalid variable redefinition:
[![https://gyazo.com/c622d47f0665483d736b31e55fc2c7a2](https://i.gyazo.com/c622d47f0665483d736b31e55fc2c7a2.png)](https://gyazo.com/c622d47f0665483d736b31e55fc2c7a2)

Repro:
```
class Foo {
  var variable:Dynamic;
}

class Bar extends Foo {
  var variable:Dynamic; // compilation error
}
```

OS: Linux Mint 17.3
IDE: Intellij Idea 14.1.6
Plugin version: 0.9.9

**Comment by anibyl** [comment]
https://github.com/TiVo/intellij-haxe/pull/432

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/549dbd87ed33263267b43fc8ef3c7cb1b8c166e9
