### ISSUE TITLE
Import type, but generic sub-types is not resolved

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#435]
When import Type, if trying to use generic sub-type - resolving failed
![image](https://cloud.githubusercontent.com/assets/3038174/13291580/5b7b02f4-db29-11e5-9c65-14202299cab8.png)

Repro:
- File `intellij.haxe.issues.sub.GenericClass`:
```
package intellij.haxe.issues.sub;
class GenericClass {}
class GenericSubClass<T> {
    public function foo() {}
}
```
- Issue class:
```
package intellij.haxe.issues;
import intellij.haxe.issues.sub.GenericClass;
class ImportGenericClass {
    public function new() {
        var a:GenericSubClass<String>;
        a.foo(); // no completion, not resolved
    }
}
```

1. If use `import intellij.haxe.issues.sub.GenericClass.GenericSubClass` - All works
2. If use `var a:GenericSubClass` what is senseless, but completion and resolving starts works

Version: 0.9.9, IDEA 14/15, OSX

But I already know how and where exactly issue can be fixed (maybe duplicated, apologize, no time to search all issues, can be root of other resolving issues)

**Comment by eliasku** [comment]
Also affected usage of Ref<..> resolving when just `import haxe.macro.Type`. After the PR with general generic typedef resolving support  will be merged - this issue fix will be awesome.

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/2de781a458006419d17f795a77c24fd4470202a3
