### ISSUE TITLE
Incorrect “public” modifier when override methods

### ISSUE THREAD

**Issue by anibyl** [TiVo/intellij-haxe#439]
When I try to override function incorrect public modifier appears always.
``Ctrl+O`` in ``Bar`` class:
[![https://gyazo.com/aa6007675c395775b1bb753585d48e4a](https://i.gyazo.com/aa6007675c395775b1bb753585d48e4a.png)](https://gyazo.com/aa6007675c395775b1bb753585d48e4a)
Then I selected all methods to override:
[![https://gyazo.com/33e974fcc6063a369a2fcaeb8ab2292f](https://i.gyazo.com/33e974fcc6063a369a2fcaeb8ab2292f.png)](https://gyazo.com/33e974fcc6063a369a2fcaeb8ab2292f)
As you can see “protected” methods became “public”.

Repro:
```
class Main {
    function protectedOperation(s:String):String { return s; }
}

class Foo extends Main {
    // press Ctrl+O here and override protectedOperation
}
```

https://github.com/TiVo/intellij-haxe/blame/master/src/common/com/intellij/plugins/haxe/ide/generation/OverrideImplementMethodFix.java#L58 was done for interfaces only.

**Comment by bynuff** [comment]
+1

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/02d8b93d24c96a08e0b01fcd89360cd377963ea0
