### ISSUE TITLE
Project options: Project type radio button click

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#44]
![Imgur](http://i.imgur.com/1RKfkkz.png)

So as you can see, after I clicked on `NMML` circle it still shows up options for `OpenFL`, when I click on `NMML` text it does works as expected.

Perhaps can be fixed just by adding corresponding handler to radiobutton if possible.
TIR: STB-7294

**Comment by EBatTiVo** [comment]
Fixed: fe5de67f621beae9f08d8032bf38571224c6de4b  PR #401 

Will be in 0.9.9 release.
