### ISSUE TITLE
Incorrect field access modifier after action generate set/get methods. Can't use action generate set/get methods for static fields.

### ISSUE THREAD

**Issue by bynuff** [TiVo/intellij-haxe#442]
Access modifier at field always become "public" after action generate set/get methods.
<img width="189" alt="before_set_get" src="https://cloud.githubusercontent.com/assets/16537796/13338839/21efd926-dc35-11e5-84af-5fdf2a90171f.png">
<img width="168" alt="after_set_get" src="https://cloud.githubusercontent.com/assets/16537796/13338858/49eca896-dc35-11e5-9a64-173174a9e6c2.png">
Static fields are not included at choose list at action generate set/get methods.
<img width="213" alt="static_field_set_get" src="https://cloud.githubusercontent.com/assets/16537796/13338905/bc90ce4a-dc35-11e5-92b5-c3b22a46c2b4.png">

**Comment by eliasku** [comment]
@bynuff please check the master version and close if it's good

**Comment by bynuff** [comment]
fixed
