### ISSUE TITLE
Forwarding abstract fields not resolved. Autocomplete don't work for forwarding abstract fields.

### ISSUE THREAD

**Issue by bynuff** [TiVo/intellij-haxe#447]
Meta @:forward not resolved with abstract forwarding fields.
<img width="365" alt="forward_not_resolved" src="https://cloud.githubusercontent.com/assets/16537796/13471863/79b4632e-e0c3-11e5-8c67-5e0f359a3d3b.png">

Forwarding abstract type not resolved.
<img width="364" alt="forward_field_not_resolved" src="https://cloud.githubusercontent.com/assets/16537796/13471942/d3a17f7a-e0c3-11e5-9026-e49dea2d0ad5.png">

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/17b83665d7be99943b1c662b70231300008db038
