### ISSUE TITLE
Incorrect error annotation in extended class for static fields and methods with same names like in base class.

### ISSUE THREAD

**Issue by bynuff** [TiVo/intellij-haxe#449]
<img width="583" alt="incorrect_annotation_error_for_static" src="https://cloud.githubusercontent.com/assets/16537796/13521413/5c89aaf2-e1f9-11e5-9eb3-66af03d9fb50.png">

**Comment by EBatTiVo** [comment]
While it isn't technically an error, I do believe that it is bad programming practice.  Perhaps we can demote it to a warning instead of removing the annotation altogether?

The code above doesn't compile, but add an @:isVar and it will: (http://try.haxe.org/#fADF6):
```haxe
class Test {
    static function main() {
    }
}

class BaseTest {
    public static var SOME_STATIC_FIELD:String = "qwer";
    
    @:isVar public static var someStaticField(get, set):String;
    
    static function get_someStaticField():String {
        return someStaticField;
    }
    
    static function set_someStaticField(value:String) {
        return someStaticField = value;
    }
    
    public static function someStaticMethod() {
    }

    public function new() {}
}

class CustomTest extends BaseTest {
    public static var SOME_STATIC_FIELD:String = "qwer";
    
    @:isVar public static var someStaticField(get, set):String;
    
    static function get_someStaticField():String {
        return someStaticField;
    }
    
    static function set_someStaticField(value:String) {
        return someStaticField = value;
    }
    
    public static function someStaticMethod() {
    }

    public function new() { super(); }
}
```

**Comment by bynuff** [comment]
@EBatTiVo  yes, you right @:isVar meta needed. Issue screenshot updated. Is this bad programming practice, yes it is. But for haxe compiler this code is valid. About warnings, I think this is not a good idea, because in java and flash in the same situation has no any warnings about it.
Java test:
<img width="372" alt="java_static_annotation_test" src="https://cloud.githubusercontent.com/assets/16537796/13521933/5c4253ba-e1fd-11e5-8beb-5bbd37fb7664.png">
Flash test:
<img width="459" alt="flash_static_annotation_test" src="https://cloud.githubusercontent.com/assets/16537796/13521947/6e68ad32-e1fd-11e5-9df1-650434a4077a.png">

**Comment by EBatTiVo** [comment]
Actually, Java has this notification; it's just turned off by default, and it's part of the Inspections process.

![image](https://cloud.githubusercontent.com/assets/7231977/13523378/f9325552-e1a9-11e5-9281-aceac0fff53a.png)

for code:
```java
class TestJavaBase{
    TestJavaBase() {
        // call static method from TestJavaBase
        someStaticJavaMethod();
    }
    static void someStaticJavaMethod() {}
}

class CustomTestJava extends TestJavaBase {
    CustomTestJava() {
        super();
        // call static method from CustomTestJava class
        someStaticJavaMethod();
        // call static method from TestJavaBase
        TestJavaBase.someStaticJavaMethod();
    }

    static void someStaticJavaMethod() {}
}
```

Javascript has a similar notification in the "Code Quality Tools" section.  I don't have Flash set up to test easily.

I think it's fine to annotate with warnings.  It could also be added to inspections.

Anybody else want to weigh in on whether we should keep it as a warning?

**Comment by bynuff** [comment]
@EBatTiVo do you want add this case to inspections process or just like warning?

**Comment by EBatTiVo** [comment]
@bynuff My preference, for the time being, is to leave it as a warning.  I don't want to make the work harder by adding it to the inspections.  I will leave you the option, though: If you would like to add it to inspections instead, that will be fine with me.

**Comment by bynuff** [comment]
@EBatTiVo I leave it as a warnings. Inspections is a big hard work, and need a lot of time to put in order this feature.

**Comment by bynuff** [comment]
@EBatTiVo check please PR

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/c728da7321f04131d61bdf824fb8114f4d394154
Will be in release 0.9.10.
