### ISSUE TITLE
Method local variables and arguments has no completion.

### ISSUE THREAD

**Issue by bynuff** [TiVo/intellij-haxe#455]
<img width="501" alt="local_method_var_no_completion" src="https://cloud.githubusercontent.com/assets/16537796/13907396/373f325a-eefe-11e5-8fee-d2703f5da772.png">

<img width="498" alt="method_args_no_completion" src="https://cloud.githubusercontent.com/assets/16537796/13907398/3fbc1bc8-eefe-11e5-8f3f-933d52c37876.png">

**Comment by EBatTiVo** [comment]
Fixed: https://github.com/TiVo/intellij-haxe/commit/4f8400a247ebcf13efd78e1ac0fb3b75a3752163
Will be in release 0.9.10.
