### ISSUE TITLE
@:deprecated support

### ISSUE THREAD

**Issue by anibyl** [TiVo/intellij-haxe#459]
There is no @:deprecated meta support (strikeout or other predefined IDE behaviour for deprecated symbols).

![https://i.gyazo.com/fbeac763902f98e3980d8a9afe886548.png](https://i.gyazo.com/fbeac763902f98e3980d8a9afe886548.png)

**Comment by anibyl** [comment]
I will submit pull-request soon.

**Comment by EBatTiVo** [comment]
Merged: https://github.com/TiVo/intellij-haxe/commit/99675789cd10363715fe8dde29c918cd16226a86
