### ISSUE TITLE
Cannot install haxe support plugin

### ISSUE THREAD

**Issue by alexdmiller** [TiVo/intellij-haxe#465]
1. Navigate to Preferences > Plugins > Browse repositories...
2. Search for `Haxe Support`, click install, restart IntelliJ
3. I get the following error:

  ```
  Plugin Error
           Problems found loading plugins:
           Following plugins are incompatible with current IDE build: Haxe Support
  ```

I'm using build 145.972 of IntelliJ.

**Comment by EBatTiVo** [comment]
Correct.  We do not have a 2016 version of the plugin yet.  See the particulars of that bug for the status, if you'd like to help.

Duplicate of #454.

**Comment by eliasku** [comment]
@alexdmiller  https://github.com/eliasku/intellij-haxe/releases/tag/v0.10.0-beta
