### ISSUE TITLE
(default,never) -> This field cannot be initialized because it is not a real variable

### ISSUE THREAD

**Issue by derRaab** [TiVo/intellij-haxe#485]
Since Haxe 3.3.0 only inline or read-only (default, never) fields can be used as a pattern - so I need to declare them with (default,never):

`public static var V_2 (default,never) : String = "v2";`

But this will be marked as an error with the message: "This field cannot be initialized because it is not a real variable", The code compiles just fine. It's a cosmetic thing but would be nice to get fixed. :)

Her a little screenshot for clarification:

![bildschirmfoto 2016-09-28 um 09 48 34](https://cloud.githubusercontent.com/assets/2079540/18905040/71475c44-8561-11e6-9a3b-4912f509f499.png)

**Comment by kodekuru** [comment]
To fix this, the method `isRealVar` in HaxeFieldModel.java can be chaged like below:
```
  public boolean isRealVar() {
    if (this.getModifiers().hasModifier(HaxeModifierType.IS_VAR)) return true;
    if (!isProperty()) return true;
    if (getGetterType() == HaxeAccessorType.NULL || getGetterType() == HaxeAccessorType.DEFAULT) {
      return true;
    }
    return false;
  }
```
