### ISSUE TITLE
Optimize imports breaks code sometimes

### ISSUE THREAD

**Issue by winmain** [TiVo/intellij-haxe#493]
When I try to optimize this code:
```haxe
import js.Browser;  // unused import
import js.Lib;
import js.Cookie;

class Test {
  public function new() {
    Cookie.all();
    Lib.debug();
  }
}
```
I got this:
```haxe
iimport js.Cookie;   // double "i"
import js.Lib;       // no blank line after imports
class Test {
  public function new() {
    Cookie.all();
    Lib.debug();
  }
}
```

The problem arises in this conditions: 1 unused import + 2 used imports. Only in this order.

Plugin version: `Pre-release candidate 0.10.1-RC1`
Idea: `2016.2`

**Comment by EBatTiVo** [comment]
@anibyl Do you want to look into this?

**Comment by anibyl** [comment]
Yes, I'll take a look.

**Comment by anibyl** [comment]
Looks like the issue is in `HaxeImportOptimizer:127`: `documentManager.doPostponedOperationsAndUnblockDocument(document);` trims document. Need to reevaluate offsets.

**Comment by anibyl** [comment]
@EBatTiVo Please look at #494

**Comment by anibyl** [comment]
Need to be closed.

**Comment by winmain** [comment]
The fix works for me. Thanks, guys!
