### ISSUE TITLE
`in` keyword is missing

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#501]
We're still miss `in` keyword inside lexer and grammar. 
For example `for(x in y) {}`
IN should be highlighted as a keyword

**Comment by as3boyan** [comment]
I am wondering how it is done, for example in case of "for"

**Comment by EBatTiVo** [comment]
It's definitely in the BNF:
```bnf
forStatement ::= 'for' '(' componentName 'in' iterable')' statement ';'?
{mixin="com.intellij.plugins.haxe.lang.psi.impl.HaxeForStatementPsiMixinImpl" implements="com.intellij.plugins.haxe.lang.psi.HaxeForStatementPsiMixin"}
// XXX: Somehow or another, forStatement must derive from AbstractHaxeNamedComponent, or variable resolution will break.
```

Colorizing is done in HaxeColorAnnotator.annotate().  There are specific tests for 'new' and 'from/to'.

> I am wondering how it is done, for example in case of "for"

for, while, break, throw, switch, etc.  are declared as "statement"s in the BNF.  They all derive from (Haxe)PsiStatement, colorizing of which must be handled by some magic performed in the IDEA implementation classes.

The trouble with 'in' is that it's not actually a statement in and of itself.  It's more of a separator between the variable name and the elements being iterated over.

**Comment by EBatTiVo** [comment]
#504 has the change.

**Comment by EBatTiVo** [comment]
Fixed with https://github.com/TiVo/intellij-haxe/commit/d670d129e40a4ea6789e4cfa9eb30bef0db0d977.
