### ISSUE TITLE
Add support for type check syntax (expr : type)

### ISSUE THREAD

**Issue by winmain** [TiVo/intellij-haxe#510]
Haxe supports [type check](https://haxe.org/manual/expression-type-check.html) since 3.1.0. It's a very handy construction, especially when you do not want to use cast. Also it should help the haxe plugin to resolve type info for autocomplete.

Some code example:

``` haxe
class Test {
  public function foo(v: Dynamic) {
    (v: Test).foo(null);  // Unresolved symbol here, no autocompletion support
  }
}
```

Plugin version: `0.10.1-RC2`
Idea: `2016.2`

**Comment by EBatTiVo** [comment]
@winmain  Can we close this?

**Comment by winmain** [comment]
Sure
