### ISSUE TITLE
OpenFL + Mac. Can't run because plugin treats innocent compiler output as error

### ISSUE THREAD

**Issue by brokenbeta** [TiVo/intellij-haxe#514]
Ok I have a feeling I might be misunderstanding this one, but I don't believe so. Basically I am running:
- IntelliJ 2016.2.5 CE
- Latest release of the plugin, 0.10.1-rc2
- On a Mac running OS X El Capitan
- JDK 1.6

I can build for Flash and Neko perfectly fine, but when I try to run a mac build, I get 3 errors reported. To explain, I took the invocation of haxelib and ran it myself in the IntelliJ output, which produces this:

```
openfl → remember ∞ /usr/local/lib/haxe/haxelib run lime build /Users/cburtbrown/Projects/tile-level-editor/project.xml mac -verbose 
 ___     
/\_ \    __                       
\//\ \  /\_\    ___ ___      __   
  \ \ \ \/\ \ /' __` __`\  /'__`\ 
   \_\ \_\ \ \/\ \/\ \/\ \/\  __/ 
   /\____\\ \_\ \_\ \_\ \_\ \____\
   \/____/ \/_/\/_/\/_/\/_/\/____/

Lime Command-Line Tools (3.2.1)

Initializing project...
Using project file: /Users/cburtbrown/Projects/tile-level-editor/project.xml
Reading HXCPP config: /Users/cburtbrown/.hxcpp_config.xml
Using target platform: MAC

Running command: UPDATE
 - Copying template file: /usr/local/lib/haxelib/lime/3,2,1/templates/haxe/ApplicationMain.hx -> bin/mac64/cpp/release/haxe/ApplicationMain.hx
 - Copying template file: /usr/local/lib/haxelib/lime/3,2,1/templates/haxe/DefaultAssetLibrary.hx -> bin/mac64/cpp/release/haxe/DefaultAssetLibrary.hx
 - Copying template file: /usr/local/lib/haxelib/openfl/4,2,0/templates/haxe/ApplicationMain.hx -> bin/mac64/cpp/release/haxe/ApplicationMain.hx
 - Copying template file: /usr/local/lib/haxelib/openfl/4,2,0/templates/haxe/NMEPreloader.hx -> bin/mac64/cpp/release/haxe/NMEPreloader.hx
 - Copying template file: /usr/local/lib/haxelib/lime/3,2,1/templates/cpp/hxml/debug.hxml -> bin/mac64/cpp/release/haxe/debug.hxml
 - Copying template file: /usr/local/lib/haxelib/lime/3,2,1/templates/cpp/hxml/final.hxml -> bin/mac64/cpp/release/haxe/final.hxml
 - Copying template file: /usr/local/lib/haxelib/lime/3,2,1/templates/cpp/hxml/release.hxml -> bin/mac64/cpp/release/haxe/release.hxml
 - Copying template file: /usr/local/lib/haxelib/lime/3,2,1/templates/mac/Info.plist -> bin/mac64/cpp/release/bin/TileEditor.app/Contents/Info.plist
 - Copying template file: /usr/local/lib/haxelib/lime/3,2,1/templates/mac/Entitlements.plist -> bin/mac64/cpp/release/bin/TileEditor.app/Contents/Entitlements.plist

Running command: BUILD
 - Copying library file: /usr/local/lib/haxelib/hxcpp/3,3,49/bin/Mac64/std.dylib -> bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/std.dylib
 - Copying library file: /usr/local/lib/haxelib/hxcpp/3,3,49/bin/Mac64/regexp.dylib -> bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/regexp.dylib
 - Copying library file: /usr/local/lib/haxelib/hxcpp/3,3,49/bin/Mac64/zlib.dylib -> bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/zlib.dylib
 - Copying library file: /usr/local/lib/haxelib/lime/3,2,1/ndll/Mac64/lime.ndll -> bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/lime.ndll
 - Running command: haxe bin/mac64/cpp/release/haxe/release.hxml -D HXCPP_CLANG -D HXCPP_M64
 - Changing directory: bin/mac64/cpp/release/obj
 - Running command: haxelib run hxcpp Build.xml -DHXCPP_CLANG=1 -DHXCPP_M64=1 -Dactuate=1.8.7 -Ddesktop=1 -Dformat=3.2.1 -Dhaxe3=1 -Dhaxe_ver=3.201 -Dhxcpp_api_level=321 -Dlime=3.2.1 -Dlime-cairo=1 -Dlime-cffi=1 -Dlime-curl=1 -Dlime-native=1 -Dlime-openal=1 -Dlime-opengl=1 -Dlime_cairo=1 -Dlime_cffi=1 -Dlime_curl=1 -Dlime_native=1 -Dlime_openal=1 -Dlime_opengl=1 -Dlinc_dialogs=0.0.0 -Dmac=1 -Dmacos=1 -Dnative=1 -Dopenfl=4.2.0 -Dopenfl-native=1 -Dopenfl_native=1 -Dswf=2.2.1 -Dtools=3.2.1 -DHXCPP_CLANG -DHXCPP_M64 -verbose
 __                          
/\ \                                      
\ \ \___    __  _   ___   _____   _____   
 \ \  _ `\ /\ \/'\ /'___\/\ '__`\/\ '__`\ 
  \ \ \ \ \\/>  <//\ \__/\ \ \L\ \ \ \L\ \
   \ \_\ \_\/\_/\_\ \____\\ \ ,__/\ \ ,__/
    \/_/\/_/\//\/_/\/____/ \ \ \/  \ \ \/ 
                            \ \_\   \ \_\ 
                             \/_/    \/_/ 

hxcpp (Haxe C++ Runtime Support) (3.3.49)

Using makefile: Build.xml
Reading HXCPP config: /Users/cburtbrown/.hxcpp_config.xml
No specified toolchain

 - Parsing include: /usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/setup.xml
 - Parsing include: /Users/cburtbrown/.hxcpp_config.xml (section "vars")
 - Running process: xcode-select --print-path
 - Parsing include: /usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/finish-setup.xml
 - Parsing makefile: /Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/Build.xml
 - Parsing include: /usr/local/lib/haxelib/hxcpp/3,3,49/build-tool/BuildCommon.xml
 - Parsing include: /usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/haxe-target.xml
 - Parsing include: /usr/local/lib/haxelib/linc_dialogs/git/linc/linc_dialogs.xml
 - Parsing include: /usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/mac-toolchain.xml
 - Parsing include: /usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/gcc-toolchain.xml
 - Adding path: /Applications/Xcode.app/Contents/Developer/usr/bin
 - Parsing compiler: /usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/common-defines.xml
 - Parsing include: /Users/cburtbrown/.hxcpp_config.xml (section "exes")

Using compile threads: 2

Creating PCH directory "/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/__pch/haxe"
 - Precompile /Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/__pch/haxe/hxcpp.h.gch
 - Running command: xcrun --sdk macosx10.11 clang++ -Iinclude -I/usr/local/lib/haxelib/linc_dialogs/git//linc -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/usr/local/lib/haxelib/hxcpp/3,3,49/include -DHX_MACOS -m64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -frtti -Wno-invalid-offsetof -x c++-header -o /Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/__pch/haxe/hxcpp.h.gch /usr/local/lib/haxelib/hxcpp/3,3,49/include/hxcpp.h
 - Compile : src/lime/AssetCache.cpp
   xcrun --sdk macosx10.11 clang++ -I/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/__pch/haxe -Iinclude -I/usr/local/lib/haxelib/linc_dialogs/git//linc -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/usr/local/lib/haxelib/hxcpp/3,3,49/include -DHX_MACOS -m64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -x c++ -frtti -Wno-invalid-offsetof ./src/lime/AssetCache.cpp -o/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/c35aa8df_AssetCache.o
 - Compile : src/ApplicationMain.cpp
   xcrun --sdk macosx10.11 clang++ -I/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/__pch/haxe -Iinclude -I/usr/local/lib/haxelib/linc_dialogs/git//linc -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/usr/local/lib/haxelib/hxcpp/3,3,49/include -DHX_MACOS -m64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -x c++ -frtti -Wno-invalid-offsetof ./src/ApplicationMain.cpp -o/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/f505ff26_ApplicationMain.o
 -  - Link : ApplicationMain: xcrun --sdk macosx10.11 clang++ -o ApplicationMain -stdlib=libstdc++ -framework Cocoa -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -m64 -framework Cocoa -framework Foundation @obj/darwin64/all_objs
 - Running command: strip -u -r -x ApplicationMain
 generated config=/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/HxcppConfig.h
 generated exe=/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/ApplicationMain
 - Copying file: bin/mac64/cpp/release/obj/ApplicationMain -> bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/TileEditor
 - Running command: chmod 755 bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/TileEditor
```

Which looks fine to me, it didn't run the app yet but clearly built it successfully. However when I run the app with Ctrl+R, it produces precisely the same output, but claims there are 3 errors in it:

```
[!]  - Compile : src/lime/AssetCache.cpp

[!]  - Compile : src/ApplicationMain.cpp

[!]  -  - Link : ApplicationMain: xcrun --sdk macosx10.11 clang++ -o ApplicationMain -stdlib=libstdc++ -framework Cocoa -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -m64 -framework Cocoa -framework Foundation @obj/darwin64/all_objs
```

![error](https://cloud.githubusercontent.com/assets/3834867/19824596/d2f89312-9d68-11e6-9862-fa9a65099e2d.png)

I have no idea why the plugin thinks these lines are errors because as far as I can see they're not errors at all, just normal compiler output.

Meanwhile the build was actually successful and the program is sitting there in bin/mac64 and runs fine. But since IntelliJ thinks the build failed it doesn't run the app which I think means getting hxcpp debugging working will be impossible.

**Comment by brokenbeta** [comment]
Also, one extra thing which might be pertinent. Probably not relevant at all but I figure why not mention it.

In the past I've had success fixing issues with the plugin by starting IntelliJ from the command line:

    open -a "IntelliJ IDEA CE"

If I do this now, and then from this instance of IntelliJ I press Run, it changes what comes up in the Messages window. The results are, um, interesting. The output from lime is completely garbled. I know it looks like I've copy-pasted this wrong, but I haven't:

    Information:___
    Information:/
    Information:\_ \    __
    Information:\//
    Information:\ \
    Information:\
    Information:_
    Information:\    ___ ___      __
    Information:\/
    Information:\ \ /' __` __`\  /'__`\
    Information:_\ \_
    Information:\  __/
    Information:\____\
    Information:\_\ \_\ \_\ \_\ \____\
    Information:\/____/ \/_/\/_/\/_/\/_/\/____/
    Information:Lime Command-Line Tools
    Information:(3.2.1)
    Information:Initializing project...
    Information:Using project file: /Users/cburtbrown/Projects/tile-level-editor/project.xml
    Information:Reading HXCPP config: /Users/cburtbrown/.hxcpp_config.xml
    Information:Using target platform: MAC
    Information:Running command: UPDATE
    Information:-
    Information:Copying template file:
    Information:/usr/local/lib/haxelib/lime/3,2,1/templates/haxe/ApplicationMain.hx
    Information:->
    Information:bin/mac64/cpp/release/haxe/ApplicationMain.hx
    Information:/usr/local/lib/haxelib/lime/3,2,1/templates/haxe/DefaultAssetLibrary.hx
    Information:bin/mac64/cpp/release/haxe/DefaultAssetLibrary.hx
    Information:/usr/local/lib/haxelib/openfl/4,2,0/templates/haxe/ApplicationMain.hx
    Information:/usr/local/lib/haxelib/openfl/4,2,0/templates/haxe/NMEPreloader.hx
    Information:bin/mac64/cpp/release/haxe/NMEPreloader.hx
    Information:/usr/local/lib/haxelib/lime/3,2,1/templates/cpp/hxml/debug.hxml
    Information:bin/mac64/cpp/release/haxe/debug.hxml
    Information:/usr/local/lib/haxelib/lime/3,2,1/templates/cpp/hxml/final.hxml
    Information:bin/mac64/cpp/release/haxe/final.hxml
    Information:/usr/local/lib/haxelib/lime/3,2,1/templates/cpp/hxml/release.hxml
    Information:bin/mac64/cpp/release/haxe/release.hxml
    Information:/usr/local/lib/haxelib/lime/3,2,1/templates/mac/Info.plist
    Information:bin/mac64/cpp/release/bin/TileEditor.app/Contents/Info.plist
    Information:/usr/local/lib/haxelib/lime/3,2,1/templates/mac/Entitlements.plist
    Information:bin/mac64/cpp/release/bin/TileEditor.app/Contents/Entitlements.plist
    Information:Running command: BUILD
    Information:Copying library file:
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/bin/Mac64/std.dylib
    Information:bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/std.dylib
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/bin/Mac64/regexp.dylib
    Information:bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/regexp.dylib
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/bin/Mac64/zlib.dylib
    Information:bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/zlib.dylib
    Information:/usr/local/lib/haxelib/lime/3,2,1/ndll/Mac64/lime.ndll
    Information:bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/lime.ndll
    Information:Running command:
    Information:haxe bin/mac64/cpp/release/haxe/release.hxml -D HXCPP_CLANG -D HXCPP_M64
    Information:Changing directory:
    Information:bin/mac64/cpp/release/obj
    Information:haxelib run hxcpp Build.xml -DHXCPP_CLANG=1 -DHXCPP_M64=1 -Dactuate=1.8.7 -Ddesktop=1 -Dformat=3.2.1 -Dhaxe3=1 -Dhaxe_ver=3.201 -Dhxcpp_api_level=321 -Dlime=3.2.1 -Dlime-cairo=1 -Dlime-cffi=1 -Dlime-curl=1 -Dlime-native=1 -Dlime-openal=1 -Dlime-opengl=1 -Dlime_cairo=1 -Dlime_cffi=1 -Dlime_curl=1 -Dlime_native=1 -Dlime_openal=1 -Dlime_opengl=1 -Dlinc_dialogs=0.0.0 -Dmac=1 -Dmacos=1 -Dnative=1 -Dopenfl=4.2.0 -Dopenfl-native=1 -Dopenfl_native=1 -Dswf=2.2.1 -Dtools=3.2.1 -DHXCPP_CLANG -DHXCPP_M64 -verbose
    Information:__
    Information:/\ \
    Information:\ \ \___    __  _   ___   _____   _____
    Information:\ \  _ `\ /\ \/'\ /'___\/\ '__`\/\ '__`\
    Information:\ \ \ \ \\/>  <//\ \__/\ \ \L\ \ \ \L\ \
    Information:\ \_\ \_\/\_/\_\ \____\\ \ ,__/\ \ ,__/
    Information:\/_/\/_/\//\/_/\/____/ \ \ \/  \ \ \/
    Information:\ \_\   \ \_\
    Information:\/_/    \/_/
    Information:hxcpp
    Information:(Haxe C++ Runtime Support)
    Information:
    Information:(3.3.49)
    Information:Using makefile: Build.xml
    Information:No specified toolchain
    Information:Parsing include:
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/setup.xml
    Information:/Users/cburtbrown/.hxcpp_config.xml (section "vars")
    Information:Running process:
    Information:xcode-select
    Information:--print-path
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/finish-setup.xml
    Information:Parsing makefile:
    Information:/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/Build.xml
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/build-tool/BuildCommon.xml
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/haxe-target.xml
    Information:/usr/local/lib/haxelib/linc_dialogs/git/linc/linc_dialogs.xml
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/mac-toolchain.xml
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/gcc-toolchain.xml
    Information:Adding path:
    Information:/Applications/Xcode.app/Contents/Developer/usr/bin
    Information:Parsing compiler:
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/toolchain/common-defines.xml
    Information:/Users/cburtbrown/.hxcpp_config.xml (section "exes")
    Information:Using compile threads: 2
    Information:Creating PCH directory "/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/__pch/haxe"
    Information:- Precompile /Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/__pch/haxe/hxcpp.h.gch
    Information:xcrun
    Information:--sdk
    Information:macosx10.11
    Information:clang++
    Information:-Iinclude
    Information:-I/usr/local/lib/haxelib/linc_dialogs/git//linc
    Information:-c
    Information:-fvisibility=hidden
    Information:-stdlib=libstdc++
    Information:-O2
    Information:-I/usr/local/lib/haxelib/hxcpp/3,3,49/include
    Information:-DHX_MACOS
    Information:-m64
    Information:-Wno-parentheses
    Information:-Wno-null-dereference
    Information:-Wno-unused-value
    Information:-Wno-format-extra-args
    Information:-Wno-bool-conversion
    Information:-DHXCPP_M64
    Information:-DHXCPP_VISIT_ALLOCS
    Information:-DHXCPP_API_LEVEL=321
    Information:-frtti
    Information:-Wno-invalid-offsetof
    Information:-x
    Information:c++-header
    Information:-o
    Information:/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/__pch/haxe/hxcpp.h.gch
    Information:/usr/local/lib/haxelib/hxcpp/3,3,49/include/
    Information:hxcpp.h
    Information:Compile :
    Information:src/ApplicationMain.cpp
    Information:-I/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/__pch/haxe
    Information:c++
    Information:./src/
    Information:ApplicationMain.cpp
    Information:-o/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/f505ff26_ApplicationMain.o
    Information:src/lime/AssetCache.cpp
    Information:./src/lime/
    Information:AssetCache.cpp
    Information:-o/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/c35aa8df_AssetCache.o
    Error: (- Link) ApplicationMain:
    Information:ApplicationMain
    Information:-framework
    Information:Cocoa
    Information:-isysroot
    Information:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
    Information:Foundation
    Information:@obj/darwin64/all_objs
    Information:strip
    Information:-u
    Information:-r
    Information:generated config=/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/obj/darwin64/HxcppConfig.h
    Information:generated exe=/Users/cburtbrown/Projects/tile-level-editor/bin/mac64/cpp/release/obj/ApplicationMain
    Information:Copying file:
    Information:bin/mac64/cpp/release/obj/ApplicationMain
    Information:bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/TileEditor
    Information:chmod 755 bin/mac64/cpp/release/bin/TileEditor.app/Contents/MacOS/TileEditor

Lots of bits and pieces seem to have been given lines to themselves.

Actually two of the "errors" have been shredded into pieces so they actually get reported correctly as Information instead of wrongly as Error. I wonder if I can find a way to garble the compiler output more so that the errors go away and IntelliJ will actually run my program. :)

**Comment by EBatTiVo** [comment]
Looks like the compiler has changed its output format.  We will have to update the regular expressions in the error detection code:  HaxeCompilerError.isInformationalMessage().  We should probably add another expression rather than replacing pCompilingStatusMessage (to remain backward compatible to older hxcpp releases).

**Comment by EBatTiVo** [comment]
BTW, I get the exact same 'split' output from the lime command header when building a test project on Linux (Ubuntu 14.04), using lime 2.9.1.  I suspect that we've got a Unicode translation problem.
