### ISSUE TITLE
"Unresolved symbol" in imports

### ISSUE THREAD

**Issue by profelis** [TiVo/intellij-haxe#55]
import haxe.macro.Printer;

http://gyazo.com/fedd9e0937bb87ff937bc75b33492bde
![image](https://cloud.githubusercontent.com/assets/7231977/4958110/ddec4c92-66aa-11e4-9007-98473ddeb4f8.png)

my custom module 

http://gyazo.com/451f69ba42871ce06dc9fae7237a07cc
![image](https://cloud.githubusercontent.com/assets/7231977/4958136/1fcd030e-66ab-11e4-8d20-3f54e6a2f1f8.png)

TIR: STB-7298

**Comment by profelis** [comment]
```import haxe.macro.Expr.Position;```

doesn't resolve too

**Comment by EBatTiVo** [comment]
haxe.macro.Tools is a class that uses static extensions and typedefs to simplify importing and coding.  I haven't found the root of the problem yet, though, since the file is on the standard classpath and should be found.

**Comment by EBatTiVo** [comment]
Fixed at ClassHierarchy e5d7d7f98c5942581db762e7138879e2762b069f

**Comment by EBatTiVo** [comment]
@profelis I think this is fixed.  Please re-open if your testing shows otherwise.
