### ISSUE TITLE
Empty lines in autocompletion

### ISSUE THREAD

**Issue by profelis** [TiVo/intellij-haxe#56]
http://gyazo.com/00be69ed96fb8fcd494e9a901c37b052

MacOS, Intellij IDEA 13, plugin from ClassHierarchy branch, this commit https://github.com/TiVo/intellij-haxe/commit/d32a63ddc7774539a638917b2a17b8cde8ff2aaf

**Comment by EBatTiVo** [comment]
Looks to me (in local testing) like this is working now.  Is anybody still seeing it?

**Comment by profelis** [comment]
Yes. Fixed
