### ISSUE TITLE
Wrong recognizing ">=" in "A<T>=something"

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#62]
1. `var p:Vector<Float> = new Vector<Float>(3);` - all right;
2. `var p:Vector<Float>=new Vector<Float>(3);` - interpreted as `>=` and without doing lookbehind for search opening bracket `<`.
![screen shot 2014-11-16 at 17 11 09](https://cloud.githubusercontent.com/assets/888526/5061712/e66d2aac-6db3-11e4-9564-90168bc13c5a.png)

**Comment by EBatTiVo** [comment]
@fzzr Have you had a chance to re-test with a newer build?  Please re-open if you still have the problem using the ClassHierarchy branch's build.

Works for Boyan and me.  I verified almost identical PSI was generated.
Closing.
