### ISSUE TITLE
Plugin locks IntelliJ IDEA 14 at 100 cpu

### ISSUE THREAD

**Issue by jasonsturges** [TiVo/intellij-haxe#67]
TiVo / Intellij-haxe plugin freezes my IntelliJ 14 at 100 cpu, seemingly forever.  Log directory is created; however, lock is significant enough that it can't produce the log file itself.

This is my first install of TiVo fork due to issues with Haxe support custom language Plugin 0.8.1 (updated August 21, 2014) hosted at JetBrians - that plugin builds, but neither run or debug configurations are functional.

Environment:
- IntelliJ IDEA Ultimate 14.0.1
- Haxe toolkit 3.1.3
- hxcpp: [3.1.39]
- lime: [2.0.0]
- openfl: [2.1.6]

TIR: STB-7301

**Comment by EBatTiVo** [comment]
Since we're now supporitng v14, this is now a bug, not an enhancement.

@jasonsturges, Tried this lately?  I don't see a lockup when I start v14 or v14.1, even with large projects.  0.9.3 is the latest release as I write this.

**Comment by EBatTiVo** [comment]
I should note that I haven't tried it on a mac.  My tests have been on Linux and Windows.

**Comment by jasonsturges** [comment]
@EBatTiVo Not recently - which distro should I test out?

**Comment by EBatTiVo** [comment]
@jasonsturges, 0.9.3, from the JetBrains plugin repository.  It's the same as the one on the TiVo repository.

**Comment by jasonsturges** [comment]
@EBatTiVo Well, my IDE loads after installing the plugin; however, neither run or debug configurations work, still giving me:

![image](https://cloud.githubusercontent.com/assets/1213591/7300164/2e12f9b4-e9a0-11e4-9e95-065bcdd72ccc.png)

**Comment by EBatTiVo** [comment]
@jasonsturges,  Just a thought.  I had the same problem with "could not process argument run".  It turned out that I had the haxelib executable entry on the SDK configuration page (Project Structure->SDKs) pointing at the haxe executable instead.

**Comment by jasonsturges** [comment]
@EBatTiVo That's possible.  Recently I've changed MacBooks, and have ended up reinstalling my entire development environment from scratch.  

Regardless whether misconfiguration or my history with Haxe had accumulated cruft, I'm excited to note I am finally able to run and debug directly from IntelliJ 14.  It's quite awesome.

Thanks.
