### ISSUE TITLE
'Invisible' errors while compiling OpenFL project

### ISSUE THREAD

**Issue by ihamer** [TiVo/intellij-haxe#76]
When I compile my project, I get two 'invisible' errors (see [more detail](https://www.evernote.com/shard/s2/sh/6f500824-885f-467b-8917-9d87490456b6/db69abaf021c98e2)). They seem to show up at the very start of the compilation process and persist until the end. My application will not run from the IDE. If I go and manually run the application, it opens up fine. I am using the latest IDEA (14.0.2) and the latest jar file.
It would be nice to get a full printout of what went wrong.

**Comment by ihamer** [comment]
@as3boyan Is there any progress on this? Currently, I cannot get any combination of Haxe plugin and IDEA to work properly, which is a shame.

**Comment by as3boyan** [comment]
@ihamer We are working on stability of Class Hierarchy branch. Still IDEA v13, and release in this repo(https://github.com/TiVo/intellij-haxe/releases) are compatible only with v13.

Also Jason from this thread, it seems like he found a workaround for IDEA v14 http://jasonsturges.com/2014/11/28/openfl-and-haxe-in-intellij-14/

**Comment by EBatTiVo** [comment]
>  Now I do not get the errors...

@ihamer, it looks like the error you first reported has been fixed -- at least on the ClassHierarchy branch.  Correct?  I'm going to close this bug and you and/or @jasonsturges  can open another one for the run target not running properly.

Just as an FYI, TiVo (I can't speak for Boyan) is using an older version of the Haxe SDK, so we may not see all of the same problems you do. If you do file a new bug, please include OS version, IDEA version, OpenFL and Haxe toolkit versions, as well as the (at least one) version string from the haxe plugin that you have failures with.

Finally, we (TiVo folks) can compile, run, and debug OpenFL projects in our environment.

**Comment by ihamer** [comment]
@EBatTiVo, thanks for the update. Would you be willing to share your combination of IDEA, Haxe SDK version, Haxe plugin, etc, so I can try to reproduce a working setup?

**Comment by EBatTiVo** [comment]
For me: 
Idea 13 (idea-IU-135.1286),
Lime tools 1.5.6
Haxe compiler 3.1.3
Haxe plugin: 0.8.1.1.TiVo.ClassHierarchy.8

Running on Kubuntu 14.04, I think: 
$ uname -a
Linux Grumpy 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

For debugging, you'll need to download the TiVo version of the debugger sources, and set up your application as stated in the README.md file (e.g. The app has to initialize a connection to the debugger).

Anything else you need?

**Comment by ihamer** [comment]
@EBatTiVo Thanks a lot for the info. 

Regarding the debugger: I suppose the instructions are at https://github.com/HaxeFoundation/hxcpp-debugger/wiki/Getting-started (the README.md in https://github.com/TiVo/debugger only says "haxe debugger haxelib").

So, I downloaded the source code from TiVo/debugger, pointed to it with haxelib dev debugger .., and followed the rest of instructions under "Basic approach". When I hit "Run" button from IDEA, I get the debugger console, and I can single step by entering "s" or continue with "c". That part seems to work. However, when I hit the Debug button I get the following, and not much else happens: 
![image](https://cloud.githubusercontent.com/assets/421051/5839072/bd84e34e-a159-11e4-91fa-2f6ac9b1c175.png)
and:
![image](https://cloud.githubusercontent.com/assets/421051/5839090/e0774aea-a159-11e4-9751-8b7b15f9fc69.png)

These are my settings. Please, let me know if you see something suspicious:
![image](https://cloud.githubusercontent.com/assets/421051/5839121/129b409e-a15a-11e4-8561-13757a8547c7.png)
![image](https://cloud.githubusercontent.com/assets/421051/5839157/62020df2-a15a-11e4-8dd2-5e883b6c0c3c.png)

**Comment by EBatTiVo** [comment]
@ihamer  We found some issues with debugging and fixed them in the last day or so.  Pick up build https://github.com/TiVo/intellij-haxe/commit/7961fd4cad4efe28eee6deea6582dbee50bdf339 and see if that helps.  As far as your settings, they look fine to me.

**Comment by ihamer** [comment]
@EBatTiVo I installed the build you pointed to, and tested on both Mac OS X and Windows 7, but could not get it to work. 

On Mac OS X:

IDEA 14 compiles the project properly but stops after printing the following in the log:
"Information:- Running command: chmod 755 Export/mac64/cpp/bin/Testproj13.app/Contents/MacOS/Testproj13"
Both "Run" and "Debug" buttons result in the same behaviour.

IDEA 13 compiles and runs the application properly. 
After I hit 'Run', I get the debugger console, and I can set breakpoints, continue, etc through the console.
When I hit 'Debug', my application window opens, then freezes. Both IDEA and the app are frozen and must be killed with "Force Quit".

On Windows 7:

IDEA 13.1.6 freezes as soon as I start typing something into a .hx file.

**Comment by ihamer** [comment]
On Ubuntu 14.04 

IDEA 13.1.6: same behaviour as on Windows. It freezes when I push "Debug". Run works well. 
I am thinking that I must be doing something wrong. But what? What is the proper procedure to start the debugging in IDEA? I have tried to push the Debug button, hoping that should do it.
Is there a way to turn on debugging within IDEA and the Haxe plugin to try to see where it fails?

One more thing: if I comment out the line new debugger.Local(true), the application opens and I see the debugger window. However, when I close the application and "Debug" it again, I get "Address already in use" error.

Would it be possible to get a sample minimal project that exercises the debugger, so I can try it out?

**Comment by ihamer** [comment]
The lockup happens only if I have a breakpoint set in IDEA. It also happens when I first try to create a breakpoint while debugging.
