### ISSUE TITLE
ClassHierarchy: When I move file from one package(dir) to another, it shows alert box with "Unimplemented" message

### ISSUE THREAD

**Issue by as3boyan** [TiVo/intellij-haxe#88]
ClassHierarchy: When I move file from one package(dir) to another, it shows alert box with "Unimplemented" message, instead it should update references(like it used to work before).

TIR: STB-7312

**Comment by EBatTiVo** [comment]
@sganapavarapu1, did you fix this today when you fixed the move test?

**Comment by EBatTiVo** [comment]
@sganapavarapu1 Sorry, you didn't fix that, Boyan did.
@as3boyan Did this bug get fixed when you fixed the 'move' unit test?

**Comment by as3boyan** [comment]
Only `testMovePackage` was fixed. I need to test it.

**Comment by as3boyan** [comment]
It was pleasure to work with IDEA and `git bisect` 858ef3adfd04a3bfb6cc8ec9e08e78b3b8e06cc6 is the first bad commit, my bad

**Comment by as3boyan** [comment]
Hopefully fixed in https://github.com/TiVo/intellij-haxe/pull/272

**Comment by EBatTiVo** [comment]
Fixed.  Merged.
