### ISSUE TITLE
Auto-adding "" {} ''

### ISSUE THREAD

**Issue by soywiz** [TiVo/intellij-haxe#90]
If are writting a ", ', ( or { character, the IDE will close it for you. There are two behaviours useful included in other languages in intelliJ:

If you write the close character just after typing the opening character, it won't write it again, just move after that character. It is useful for people that is not used to autocompletion and will prevent stuff like """". That also breaks the coloring.

The other behaviour: If you delete one of the "" it will remove the other. That helps if you typed it by error. Also makes it harder to breaking autocompletion like the other case.

**Comment by EBatTiVo** [comment]
This is a basic feature of IDEA and controlled via the editor settings: File->Settings->Editor->Smart Keys->Insert Pair Bracket, and Insert Pair Quote.
