### ISSUE TITLE
Code inside of preprocessing tokens is being ignored.

### ISSUE THREAD

**Issue by WeyskoteFoundation** [TiVo/intellij-haxe#91]
![haxe](https://cloud.githubusercontent.com/assets/4976223/5554222/394edf4c-8c2f-11e4-9c83-7e868e3caaa2.png)

**Comment by EBatTiVo** [comment]
This /was/ a bug in an older version.  It's working correctly as of Build 0.8.1.1.TiVo.ClassHierarchy.11.
