### ISSUE TITLE
meta + typedef unexpected

### ISSUE THREAD

**Issue by eliasku** [TiVo/intellij-haxe#94]
![image](https://cloud.githubusercontent.com/assets/3038174/5567334/b7cefe98-8f53-11e4-8cb9-2af565877fa6.png)

repro:
``` haxe
@:dox(hide) typedef MyInt2 = Int;
```

https://github.com/eliasku/horror/blob/master/tests/intellijhaxe/MetaTypedefIssue.hx

TIR: STB-7314

**Comment by EBatTiVo** [comment]
In haxe.bnf, typedefDeclaration doesn't include macroClassList.  Might be as simple as that.

**Comment by as3boyan** [comment]
The thing is that macro can be used almost anywhere.

**Comment by as3boyan** [comment]
I can't generate haxe.bnf without errors, I even reverted changes made in my commit, https://github.com/EBatTiVo/intellij-haxe/commit/93abe6263300944fef69ec70f5c06c603eb0d749, @EBatTiVo please take a look, does it work for you, without errors?

**Comment by EBatTiVo** [comment]
Just generated fine for me at HEAD: https://github.com/TiVo/intellij-haxe/commit/e82349e7a70173a869e09d97057be668cd0ff2d2

I'm still on IDEA13: IU-135.1286

**Comment by EBatTiVo** [comment]
> Just generated fine for me...

Except that the copyright notice just updated the year on every file.  :(
If you update the BNF, then update the copyrights as a separate change, please.

**Comment by Simn** [comment]
@as3boyan: "The thing is that meta tags can be used almost anywhere."

This is not accurate. Metadata may appear in the following places:

* before a type declaration (`class`, `enum`, `typedef`, `abstract`)
* before class fields (in classes and abstracts as well as in structures if they use class field notation)
* before enum fields
* before any expression

Any number of metadata is allowed in these places. In general: when in doubt, check the official Haxe parser.

**Comment by EBatTiVo** [comment]
> I can't generate haxe.bnf without errors,

Srikanth was having the same problem.  It turned out that the problem was two-fold:  the last time the BNF was updated, the parser files weren't regenerated, and a new function was not overridden in the non-generated files; second, he was using a newer version of the Grammar-Kit plugin than I was.

The first problem, I fixed and have already pushed to the ClassHierarchy branch.  Srikanth has fixed the issues with generating via the new Grammar-Kit plugin and those should get to ClassHierarchy today.

**Comment by as3boyan** [comment]
@simn Thanks for info.

@EBatTiVo I made some changes in some commit and didn't regenerated it, sorry, recently(maybe week ago) I tried to revert changes I made but still was unable to generate it

**Comment by as3boyan** [comment]
@eliasku Please pull changes in your fork, thanks

**Comment by as3boyan** [comment]
I pushed some fixes to haxe.bnf, and made related changes in parser utils to make it work, should work I think...
762a637caee7b84a4082a51c7116e8c5960550d1

**Comment by as3boyan** [comment]
meta tags for typedef support: https://github.com/EBatTiVo/intellij-haxe/commit/9e6c363a786a69316951a793789543572d058628

I had to change typedef pin from 2 to 5, not sure, I need better understanding of pins

**Comment by eliasku** [comment]
Fixed for 0.9.9
![image](https://cloud.githubusercontent.com/assets/3038174/13174595/e01ec328-d715-11e5-8d4a-10c7f87e96b4.png)
