### ISSUE TITLE
[HXML] import other hxml look like incorrect

### ISSUE THREAD

**Issue by fzzr-** [TiVo/intellij-haxe#97]
For reproduce use [latest build](https://github.com/TiVo/intellij-haxe/blob/ClassHierarchy/intellij-haxe.jar) of plugin and Idea 14 (IU-139.872.1)
![screen shot 2015-01-03 at 16 04 20](https://cloud.githubusercontent.com/assets/888526/5602504/b58ecd9e-9362-11e4-873f-ee87105e4339.png)

TIR: STB-7317

**Comment by fzzr-** [comment]
Tooltip:
![screen shot 2015-01-03 at 16 06 02](https://cloud.githubusercontent.com/assets/888526/5602509/df0e2660-9362-11e4-9786-65d1e0f04949.png)

**Comment by as3boyan** [comment]
ok, will be added

**Comment by eliasku** [comment]
FIXED in 0.9.9

![image](https://cloud.githubusercontent.com/assets/3038174/13174532/453b0556-d715-11e5-815b-a8526ff61c84.png)

**Comment by EBatTiVo** [comment]
> If your complain not referenced to HXML runner and project updater automation...

@eliasku That comment is confusing.  I parsed it as:  "If your complaint was not about the HXML runner or project updater automation..."  What is the rest of the statement that the elipsis (...) is alluding to?  (e.g. what is the 'then' clause?)

**Comment by eliasku** [comment]
@EBatTiVo Apologize.
@fzzr- If you have no complains about HXML runner and HXML project updater then we should close the issue.

**Comment by EBatTiVo** [comment]
No response from @fzzr- and this was fixed for the last release.  Closing.  Please re-open if the issue recurs.
