### ISSUE TITLE
macro haxe Syntax

### ISSUE THREAD

**Issue by Faba-network** [TiVo/intellij-haxe#98]
The plugin need the new „macro“ keyword so you can things like:

marco public static function test():Void{

}

If try to fix it myself but don´t have much luck of it, perhaps you can spend some time or give me an hint.

**Comment by as3boyan** [comment]
It's already fixed in ClassHierarchy branch, we just need to make sure everything is stable before releasing something.

**Comment by Faba-network** [comment]
Allright, thank you
